import { expect, test, type Page } from '@playwright/test'
import path from 'node:path'

const suffix = Date.now().toString().slice(-7)
const slug = `harbour-${suffix}`
const adminEmail = `admin-${suffix}@hearts.test`
const teacherEmail = `teacher-${suffix}@hearts.test`
const learnerEmail = `learner-${suffix}@hearts.test`
const otherEmail = `other-${suffix}@hearts.test`
const parentEmail = `parent-${suffix}@hearts.test`
const teacherCode = `H${suffix}T`
const adminCode = `H${suffix}A`
const learnerCode = `H${suffix}L`
const parentCode = `H${suffix}P`

async function signIn(page: Page, email: string, password: string, next: string) {
  await page.goto(`/login?next=${encodeURIComponent(next)}`)
  await page.getByTestId('login-email').fill(email)
  await page.getByTestId('login-password').fill(password)
  await page.getByTestId('login-submit').click()
}

test.describe.serial('HEARTS portal journeys', () => {
  test('empty sign-in is refused', async ({ page }) => {
    await page.goto('/login')
    await page.getByTestId('login-email').evaluate((el) => el.removeAttribute('required'))
    await page.getByTestId('login-password').evaluate((el) => el.removeAttribute('required'))
    await page.getByTestId('login-submit').click()
    await expect(page.getByTestId('error')).toBeVisible()
  })

  test('master opens a portal and generates codes', async ({ page }) => {
    await signIn(page, 'master@hearts.test', 'hearts-master', '/master')
    await expect(page.getByRole('heading', { name: 'Master desk' })).toBeVisible()
    await page.getByTestId('create-portal-name').fill(`Harbour ${suffix}`)
    await page.getByTestId('create-portal-slug').fill(slug)
    await page.getByTestId('create-portal-submit').click()
    await expect(page.getByTestId('notice')).toContainText('open')
    const card = page.getByTestId('portal-card').filter({ hasText: slug })
    await card.getByTestId('portal-pack-title').fill('Harbour sittings')
    await card.getByRole('button', { name: 'Save pack' }).click()
    await expect(page.getByTestId('notice')).toContainText('Course pack')
    const again = page.getByTestId('portal-card').filter({ hasText: slug })
    await again.getByTestId('code-value').fill(teacherCode)
    await again.getByTestId('code-role').selectOption('teacher')
    await again.getByTestId('code-pack').selectOption({ label: 'Harbour sittings' })
    await again.getByTestId('create-code').click()
    await expect(page.getByTestId('notice')).toContainText(teacherCode)
    const adminCard = page.getByTestId('portal-card').filter({ hasText: slug })
    await adminCard.getByTestId('code-value').fill(adminCode)
    await adminCard.getByTestId('code-role').selectOption('admin')
    await adminCard.getByTestId('code-pack').selectOption({ label: 'Harbour sittings' })
    await adminCard.getByTestId('create-code').click()
    await expect(page.getByTestId('notice')).toContainText(adminCode)
    const learnCard = page.getByTestId('portal-card').filter({ hasText: slug })
    await learnCard.getByTestId('code-value').fill(learnerCode)
    await learnCard.getByTestId('code-role').selectOption('learner')
    await learnCard.getByTestId('code-pack').selectOption({ label: 'Harbour sittings' })
    await learnCard.getByTestId('code-teacher').selectOption({ label: teacherCode })
    await learnCard.getByTestId('create-code').click()
    await expect(page.getByTestId('notice')).toContainText(learnerCode)
  })

  test('admin builds a local course, links a library film, and places questions', async ({ page }) => {
    await page.goto(`/join?code=${adminCode}`)
    await page.getByTestId('join-name').fill('Harbour Admin')
    await page.getByTestId('join-email').fill(adminEmail)
    await page.getByTestId('join-password').fill('harbour-admin')
    await page.getByTestId('join-submit').click()
    await expect(page.getByTestId('admin-overview')).toBeVisible()
    await expect(page.getByTestId('org-name')).toContainText('Harbour')
    await expect(page.getByTestId('own-courses')).toHaveText('0')
    await expect(page.getByTestId('portal-address')).toContainText(`/p/${slug}`)
    await expect(page.getByTestId('portal-qr')).toBeVisible()
    await page.getByRole('link', { name: 'Courses' }).click()
    await page.getByTestId('local-course-title').fill('Night class')
    await page.getByTestId('local-course-duration').fill('8')
    await page.getByTestId('local-course-pack').selectOption({ label: 'Harbour sittings' })
    await page.getByTestId('local-course-submit').click()
    await expect(page.getByTestId('notice')).toContainText('Course saved')
    await expect(page.getByTestId('course-row').filter({ hasText: 'Night class' })).toHaveAttribute('data-origin', 'local')
    await page.getByRole('link', { name: 'Adopt' }).click()
    await page.getByTestId('adopt-course').first().click()
    await expect(page.getByTestId('notice')).toContainText('linked')
    await expect(page.locator('[data-origin="imported"]').first()).toBeVisible()
    await page.getByRole('link', { name: 'Night class' }).click()
    await expect(page.getByTestId('youtube-url')).toBeVisible()
    await page.getByTestId('youtube-url').fill('not a link')
    await page.getByTestId('ingest-submit').click()
    await expect(page.getByTestId('error')).toContainText('YouTube')
    await page.getByTestId('youtube-url').fill('https://example.com/screenrock-share')
    await page.getByTestId('ingest-submit').click()
    await expect(page.getByTestId('error')).toContainText('did not fetch')
    await page.getByTestId('transcript-file').setInputFiles(path.join(process.cwd(), 'content/transcripts/fahmy-session6.md'))
    await page.getByTestId('transcript-submit').click()
    await expect(page.getByTestId('has-transcript')).toBeVisible()
    await page.getByTestId('extract-submit').click()
    await expect(page.getByTestId('cut-draft').first()).toBeVisible({ timeout: 60_000 })
    await page.getByTestId('approve-cut').first().click()
    await expect(page.getByTestId('notice')).toContainText('Cut updated')
    await expect(async () => {
      await page.getByTestId('preview-play').click()
      await expect(page.getByTestId('preview-readout')).not.toHaveText('0:00', { timeout: 1500 })
    }).toPass({ timeout: 15000 })
    await page.getByTestId('preview-pause').click()
    await page.getByTestId('point-timestamp').fill('2')
    await page.getByTestId('point-prompt').fill('What is one manner you want to keep?')
    await page.getByTestId('point-timing').selectOption('immediate')
    await page.getByTestId('point-submit').click()
    await expect(page.getByTestId('notice')).toContainText('Question placed')
    await expect(async () => {
      await page.getByTestId('preview-play').click()
      await expect(page.getByTestId('preview-readout')).not.toHaveText('0:00', { timeout: 1500 })
    }).toPass({ timeout: 15000 })
    await page.getByTestId('preview-pause').click()
    await page.getByTestId('point-timestamp').fill('6')
    await page.getByTestId('point-prompt').fill('What changed after two weeks?')
    await page.getByTestId('point-timing').selectOption('future')
    await page.getByTestId('point-delay').fill('2')
    await page.getByTestId('point-contingent').selectOption({ index: 1 })
    await page.getByTestId('point-submit').click()
    await expect(page.getByTestId('point-row').filter({ hasText: 'two weeks' })).toBeVisible()
    await page.goto(`/p/${slug}/admin/courses`)
    await page.locator('[data-origin="imported"] a').first().click()
    await expect(page.getByTestId('readonly')).toBeVisible()
    await expect(page.getByTestId('youtube-url')).toHaveCount(0)
    await page.getByTestId('point-prompt').fill('A question only for one learner')
    await page.getByTestId('point-audience').selectOption('self')
    await page.getByTestId('point-submit').click()
    await expect(page.getByTestId('notice')).toContainText('Question placed')
    await page.goto(`/p/${slug}/admin/settings`)
    await page.getByTestId('learner-welcome').fill('https://www.youtube.com/watch?v=MK5q_zMiX1g')
    await page.getByTestId('learner-intro').fill('https://www.youtube.com/watch?v=ECaTWkof57E')
    await page.getByTestId('teacher-welcome').fill('https://www.youtube.com/watch?v=ECaTWkof57E')
    await page.getByTestId('teacher-intro').fill('https://www.youtube.com/watch?v=MK5q_zMiX1g')
    await page.getByTestId('save-settings').click()
    await expect(page.getByTestId('notice')).toContainText('saved')
  })

  test('learner sees only the pack, answers, and meets a locked question', async ({ page }) => {
    await page.goto(`/join?code=${learnerCode}`)
    await page.getByTestId('join-name').fill('Harbour Learner')
    await page.getByTestId('join-email').fill(learnerEmail)
    await page.getByTestId('join-password').fill('harbour-learner')
    await page.getByTestId('join-submit').click()
    await expect(page.getByTestId('welcome-film')).toBeVisible()
    await page.getByTestId('welcome-continue').click()
    await expect(page.getByTestId('placing-question').first()).toBeVisible()
    const questions = page.getByTestId('placing-question')
    const count = await questions.count()
    for (let index = 0; index < count; index += 1) {
      await questions.nth(index).locator('input[type=radio]').first().check()
    }
    await page.getByTestId('placing-submit').click()
    await expect(page.getByTestId('feed-cut').first()).toBeVisible()
    await page.getByRole('link', { name: 'Path' }).click()
    await expect(page.getByTestId('visible-courses')).toHaveText('1 course open to you')
    await expect(page.getByTestId('path-course')).toContainText('Night class')
    await expect(page.getByText('How to Live Like the Prophet')).toHaveCount(0)
    await page.getByTestId('lesson-link').click()
    await page.getByTestId('mark-sat').click()
    await expect(page.getByTestId('error')).toContainText('most of the film')
    await page.getByTestId('answer-text').fill('I want to keep a soft greeting.')
    await page.getByTestId('answer-share').check()
    await page.getByTestId('answer-submit').click()
    await expect(page.getByTestId('notice')).toContainText('workbook')
    await expect(page.locator('[data-testid="point-state"][data-state="countdown"]')).toContainText('two weeks')
    await expect(page.getByTestId('countdown')).toContainText('Time to unlock')
    await page.getByTestId('clock-iso').fill('2027-01-01T00:00:00.000Z')
    await page.getByTestId('clock-submit').click()
    await expect(page.locator('[data-testid="point-state"][data-state="open"]').filter({ hasText: 'two weeks' })).toBeVisible()
    await expect(page.getByTestId('countdown')).toHaveCount(0)
    await page.getByTestId('answer-text').fill('The greeting stayed.')
    await page.getByTestId('answer-submit').click()
    await page.getByTestId('complete-full').click()
    await expect(page.getByTestId('notice')).toContainText('sat with')
    await page.getByRole('link', { name: 'Grow' }).click()
    await expect(page.getByTestId('clause-map')).toBeVisible()
    await page.getByRole('link', { name: 'Plan' }).click()
    await page.getByTestId('schedule-start').fill('2026-10-07')
    await page.getByTestId('schedule-end').fill('2026-10-16')
    await page.getByTestId('weekday-3').check()
    await page.getByTestId('weekday-5').check()
    await page.getByTestId('schedule-submit').click()
    await expect(page.getByTestId('schedule-slot').first()).toBeVisible()
    await page.goto(`/p/east-london/feed`)
    await expect(page.getByTestId('error')).toContainText('not yours')
  })

  test('a second learner sees the shared answer and not a private one', async ({ page }) => {
    await page.goto(`/join?code=${learnerCode}`)
    await page.getByTestId('join-name').fill('Second Learner')
    await page.getByTestId('join-email').fill(otherEmail)
    await page.getByTestId('join-password').fill('harbour-learner')
    await page.getByTestId('join-submit').click()
    await page.getByTestId('welcome-continue').click()
    const questions = page.getByTestId('placing-question')
    const count = await questions.count()
    for (let index = 0; index < count; index += 1) {
      await questions.nth(index).locator('input[type=radio]').first().check()
    }
    await page.getByTestId('placing-submit').click()
    await page.getByRole('link', { name: 'Path' }).click()
    await page.getByTestId('lesson-link').click()
    await expect(page.getByTestId('swarm-item').filter({ hasText: 'soft greeting' })).toBeVisible()
    await page.getByTestId('answer-text').fill('This one stays with me.')
    await page.getByTestId('answer-private').check()
    await page.getByTestId('answer-submit').click()
    await signIn(page, learnerEmail, 'harbour-learner', `/p/${slug}/path`)
    await page.getByTestId('lesson-link').click()
    const manner = page.locator('[data-testid="point-state"]').filter({ hasText: 'one manner' })
    await expect(manner).toContainText('soft greeting')
    await expect(manner).not.toContainText('stays with me')
  })

  test('parent code carries one course and a teacher can reply', async ({ page }) => {
    await signIn(page, adminEmail, 'harbour-admin', `/p/${slug}/admin/courses`)
    await page.getByTestId('local-course-title').fill('Second sitting')
    await page.getByTestId('local-course-duration').fill('8')
    await page.getByTestId('local-course-pack').selectOption({ label: 'Harbour sittings' })
    await page.getByTestId('local-course-submit').click()
    await page.goto(`/p/${slug}/admin/codes`)
    await page.getByTestId('new-code').fill(parentCode)
    await page.getByTestId('new-code-role').selectOption('parent')
    await page.getByTestId('new-code-pack').selectOption({ label: 'Harbour sittings' })
    await page.getByTestId('new-code-teacher').selectOption({ label: teacherCode })
    await page.getByTestId('new-code-submit').click()
    await expect(page.getByTestId('error')).toContainText('exactly one course')
    await page.getByTestId('portal-pack-title').fill('Parent pack')
    await page.getByTestId('portal-pack-submit').click()
    await page.goto(`/p/${slug}/admin/courses`)
    await page.getByTestId('local-course-title').fill('Parent sitting')
    await page.getByTestId('local-course-duration').fill('8')
    await page.getByTestId('local-course-pack').selectOption({ label: 'Parent pack' })
    await page.getByTestId('local-course-submit').click()
    await page.goto(`/p/${slug}/admin/codes`)
    await page.getByTestId('new-code').fill(parentCode)
    await page.getByTestId('new-code-role').selectOption('parent')
    await page.getByTestId('new-code-pack').selectOption({ label: 'Parent pack' })
    await page.getByTestId('new-code-teacher').selectOption({ label: teacherCode })
    await page.getByTestId('new-code-submit').click()
    await expect(page.getByTestId('share-url').filter({ hasText: parentCode })).toBeVisible()
    await page.goto(`/join?code=${parentCode}`)
    await page.getByTestId('join-name').fill('Harbour Parent')
    await page.getByTestId('join-email').fill(parentEmail)
    await page.getByTestId('join-password').fill('harbour-parent')
    await page.getByTestId('join-submit').click()
    if (await page.getByTestId('welcome-film').isVisible()) await page.getByTestId('welcome-continue').click()
    const questions = page.getByTestId('placing-question')
    const count = await questions.count()
    for (let index = 0; index < count; index += 1) {
      await questions.nth(index).locator('input[type=radio]').first().check()
    }
    await page.getByTestId('placing-submit').click()
    await page.getByRole('link', { name: 'Path' }).click()
    await expect(page.getByTestId('visible-courses')).toHaveText('1 course open to you')
    await expect(page.getByTestId('path-course')).toContainText('Parent sitting')
    await page.goto(`/join?code=${teacherCode}`)
    await page.getByTestId('join-name').fill('Harbour Teacher')
    await page.getByTestId('join-email').fill(teacherEmail)
    await page.getByTestId('join-password').fill('harbour-teacher')
    await page.getByTestId('join-submit').click()
    await page.getByRole('link', { name: 'Teach' }).click()
    await expect(page.getByTestId('learner-row').first()).toBeVisible()
    await page.getByTestId('reply-text').first().fill('Keep that greeting. It is enough.')
    await page.getByTestId('reply-submit').first().click()
    await expect(page.getByTestId('notice')).toContainText('Reply saved')
  })

  test('deactivating the portal blocks a learner', async ({ page }) => {
    await signIn(page, 'master@hearts.test', 'hearts-master', '/master')
    const card = page.getByTestId('portal-card').filter({ hasText: slug })
    await card.getByTestId('deactivate-portal').click()
    await expect(page.getByTestId('notice')).toContainText('deactivated')
    await signIn(page, learnerEmail, 'harbour-learner', `/p/${slug}/feed`)
    await expect(page.getByTestId('portal-closed')).toBeVisible()
    await signIn(page, 'master@hearts.test', 'hearts-master', '/master')
    await page.getByTestId('portal-card').filter({ hasText: slug }).getByTestId('deactivate-portal').click()
    await expect(page.getByTestId('notice')).toContainText('active')
  })

  test('seeded rooms stay apart', async ({ page }) => {
    await signIn(page, 'elm-learner@hearts.test', 'portal-learner', '/p/east-london/feed')
    await expect(page.getByTestId('feed-cut').first()).toBeVisible()
    await page.goto('/p/leeds/feed')
    await expect(page.getByTestId('error')).toContainText('not yours')
    await signIn(page, 'leeds-learner@hearts.test', 'portal-learner', '/p/leeds/path')
    await expect(page.getByTestId('path-course').first()).toBeVisible()
    await page.goto('/p/east-london/chapter')
    await expect(page.getByTestId('error')).toContainText('not yours')
  })
})

