import { MigrateUpArgs, MigrateDownArgs, sql } from '@payloadcms/db-postgres'

/** Queue for S3 / disk objects that failed to delete after a wipe. Identity so Postgres can insert without an id. */
export async function up({ db }: MigrateUpArgs): Promise<void> {
  await db.execute(sql.raw(`
    CREATE TABLE IF NOT EXISTS erase_s3_retries (
      id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      object_key varchar NOT NULL,
      bucket varchar,
      filename varchar,
      local_path varchar,
      error varchar,
      created_at timestamp DEFAULT CURRENT_TIMESTAMP,
      attempts integer DEFAULT 0
    );
  `))
}

export async function down({ db }: MigrateDownArgs): Promise<void> {
  await db.execute(sql.raw('DROP TABLE IF EXISTS erase_s3_retries;'))
}
