/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    portals: Portal;
    users: User;
    media: Media;
    clauses: Clause;
    seats: Seat;
    'shelf-items': ShelfItem;
    courses: Course;
    units: Unit;
    lessons: Lesson;
    resources: Resource;
    packs: Pack;
    cuts: Cut;
    'ladder-items': LadderItem;
    'engagement-points': EngagementPoint;
    answers: Answer;
    'workbook-entries': WorkbookEntry;
    notifications: Notification;
    'access-codes': AccessCode;
    adoptions: Adoption;
    'placing-questions': PlacingQuestion;
    'placing-answers': PlacingAnswer;
    tags: Tag;
    'harvest-entries': HarvestEntry;
    schedules: Schedule;
    events: Event;
    rsvps: Rsvp;
    checkins: Checkin;
    messages: Message;
    completions: Completion;
    'feedback-notes': FeedbackNote;
    'watch-sessions': WatchSession;
    'lesson-visits': LessonVisit;
    'seat-visits': SeatVisit;
    rituals: Ritual;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    portals: PortalsSelect<false> | PortalsSelect<true>;
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    clauses: ClausesSelect<false> | ClausesSelect<true>;
    seats: SeatsSelect<false> | SeatsSelect<true>;
    'shelf-items': ShelfItemsSelect<false> | ShelfItemsSelect<true>;
    courses: CoursesSelect<false> | CoursesSelect<true>;
    units: UnitsSelect<false> | UnitsSelect<true>;
    lessons: LessonsSelect<false> | LessonsSelect<true>;
    resources: ResourcesSelect<false> | ResourcesSelect<true>;
    packs: PacksSelect<false> | PacksSelect<true>;
    cuts: CutsSelect<false> | CutsSelect<true>;
    'ladder-items': LadderItemsSelect<false> | LadderItemsSelect<true>;
    'engagement-points': EngagementPointsSelect<false> | EngagementPointsSelect<true>;
    answers: AnswersSelect<false> | AnswersSelect<true>;
    'workbook-entries': WorkbookEntriesSelect<false> | WorkbookEntriesSelect<true>;
    notifications: NotificationsSelect<false> | NotificationsSelect<true>;
    'access-codes': AccessCodesSelect<false> | AccessCodesSelect<true>;
    adoptions: AdoptionsSelect<false> | AdoptionsSelect<true>;
    'placing-questions': PlacingQuestionsSelect<false> | PlacingQuestionsSelect<true>;
    'placing-answers': PlacingAnswersSelect<false> | PlacingAnswersSelect<true>;
    tags: TagsSelect<false> | TagsSelect<true>;
    'harvest-entries': HarvestEntriesSelect<false> | HarvestEntriesSelect<true>;
    schedules: SchedulesSelect<false> | SchedulesSelect<true>;
    events: EventsSelect<false> | EventsSelect<true>;
    rsvps: RsvpsSelect<false> | RsvpsSelect<true>;
    checkins: CheckinsSelect<false> | CheckinsSelect<true>;
    messages: MessagesSelect<false> | MessagesSelect<true>;
    completions: CompletionsSelect<false> | CompletionsSelect<true>;
    'feedback-notes': FeedbackNotesSelect<false> | FeedbackNotesSelect<true>;
    'watch-sessions': WatchSessionsSelect<false> | WatchSessionsSelect<true>;
    'lesson-visits': LessonVisitsSelect<false> | LessonVisitsSelect<true>;
    'seat-visits': SeatVisitsSelect<false> | SeatVisitsSelect<true>;
    rituals: RitualsSelect<false> | RitualsSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {};
  globalsSelect: {};
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "portals".
 */
export interface Portal {
  id: number;
  name: string;
  slug: string;
  kind?: ('mosque' | 'church' | 'synagogue' | 'other') | null;
  welcome?: string | null;
  colour?: string | null;
  watchHistoryOptIn?: boolean | null;
  organisationName?: string | null;
  description?: string | null;
  closed?: boolean | null;
  logoUrl?: string | null;
  showOthersAnswers?: boolean | null;
  notificationEmails?: string | null;
  theme?: ('light' | 'dark') | null;
  calendarUrl?: string | null;
  learnerWelcomeUrl?: string | null;
  learnerIntroUrl?: string | null;
  teacherWelcomeUrl?: string | null;
  teacherIntroUrl?: string | null;
  learnerLabel?: string | null;
  teacherLabel?: string | null;
  wizardDone?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  name: string;
  role: 'master' | 'portal-admin' | 'teacher' | 'learner';
  accessCode?: (number | null) | AccessCode;
  extraPacks?: (number | Pack)[] | null;
  onboarded?: boolean | null;
  seenWelcome?: boolean | null;
  startingClause?: number | null;
  courseList?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  extraCourses?: (number | Course)[] | null;
  audience?: string | null;
  shareWatch?: boolean | null;
  joinedAt?: string | null;
  nightAlerts?: boolean | null;
  tenants?:
    | {
        tenant: number | Portal;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  resetPasswordRequestedAt?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "access-codes".
 */
export interface AccessCode {
  id: number;
  portal?: (number | null) | Portal;
  code: string;
  role: 'learner' | 'teacher' | 'admin' | 'parent';
  packs?: (number | Pack)[] | null;
  requiredCourses?: (number | Course)[] | null;
  linkedTeacherCode?: (number | null) | AccessCode;
  parentMentorCode?: (number | null) | AccessCode;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "packs".
 */
export interface Pack {
  id: number;
  title: string;
  summary?: string | null;
  owner: 'master' | 'portal';
  portal?: (number | null) | Portal;
  courses?: (number | Course)[] | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "courses".
 */
export interface Course {
  id: number;
  title: string;
  summary?: string | null;
  speaker?: string | null;
  origin: 'master' | 'local';
  portal?: (number | null) | Portal;
  importable?: boolean | null;
  isPublic?: boolean | null;
  importToken?: string | null;
  hidden?: boolean | null;
  visibility?: ('draft' | 'published') | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  alt?: string | null;
  portal?: (number | null) | Portal;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "clauses".
 */
export interface Clause {
  id: number;
  number: number;
  fragment: string;
  core?: string | null;
  teaching?: string | null;
  series?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "seats".
 */
export interface Seat {
  id: number;
  clause: number | Clause;
  position: number;
  text: string;
  note?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "shelf-items".
 */
export interface ShelfItem {
  id: number;
  volume?: string | null;
  section?: string | null;
  title: string;
  series?: string | null;
  empty?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "units".
 */
export interface Unit {
  id: number;
  title: string;
  course: number | Course;
  order?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "lessons".
 */
export interface Lesson {
  id: number;
  title: string;
  unit: number | Unit;
  course: number | Course;
  portal?: (number | null) | Portal;
  master?: boolean | null;
  order?: number | null;
  speaker?: string | null;
  youtubeUrl?: string | null;
  youtubeId?: string | null;
  /**
   * Mux-ready. Unused until a Mux asset is attached.
   */
  muxAssetId?: string | null;
  muxPlaybackId?: string | null;
  durationSeconds?: number | null;
  transcript?: string | null;
  transcriptSource?: ('none' | 'youtube' | 'upload') | null;
  transcriptNote?: string | null;
  sourceUrl?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "resources".
 */
export interface Resource {
  id: number;
  lesson: number | Lesson;
  name: string;
  kind?: ('link' | 'file') | null;
  url?: string | null;
  showAtEnd?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "cuts".
 */
export interface Cut {
  id: number;
  lesson: number | Lesson;
  course?: (number | null) | Course;
  status?: ('draft' | 'approved' | 'rejected') | null;
  start: number;
  end: number;
  timestamp?: string | null;
  hook: string;
  turn: string;
  land: string;
  fullContext?: string | null;
  theme?: string | null;
  device?: string | null;
  whyItAllures?: string | null;
  bestClause?: number | null;
  clauseFragment?: string | null;
  hangStrength?: string | null;
  whyHang?: string | null;
  seatHint?: string | null;
  stage2Form?: string | null;
  currencyNote?: string | null;
  quoteConfidence?: string | null;
  exemplarAffinity?: string | null;
  kind?: string | null;
  engine?: string | null;
  seat?: (number | null) | Seat;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ladder-items".
 */
export interface LadderItem {
  id: number;
  lesson: number | Lesson;
  cut?: (number | null) | Cut;
  kind?: ('hors' | 'appetiser') | null;
  start?: number | null;
  end?: number | null;
  quote?: string | null;
  status?: ('draft' | 'approved' | 'rejected') | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "engagement-points".
 */
export interface EngagementPoint {
  id: number;
  lesson: number | Lesson;
  second: number;
  kind?: ('question' | 'multiple_choice' | 'reflection' | 'task') | null;
  prompt: string;
  options?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  timing?: ('immediate' | 'future') | null;
  delayAmount?: number | null;
  delayUnit?: ('second' | 'minute' | 'hour' | 'day' | 'week') | null;
  contingent?: (number | null) | EngagementPoint;
  link?: string | null;
  timeLimit?: number | null;
  author?: (number | null) | User;
  audience?: ('everyone' | 'self' | 'selected') | null;
  audienceUsers?: (number | User)[] | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "answers".
 */
export interface Answer {
  id: number;
  portal?: (number | null) | Portal;
  point: number | EngagementPoint;
  user: number | User;
  lesson?: (number | null) | Lesson;
  body?: string | null;
  choice?: string | null;
  image?: (number | null) | Media;
  audio?: (number | null) | Media;
  video?: (number | null) | Media;
  keepPrivate?: boolean | null;
  shareWithTeacher?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "workbook-entries".
 */
export interface WorkbookEntry {
  id: number;
  portal?: (number | null) | Portal;
  user: number | User;
  answer?: (number | null) | Answer;
  lesson?: (number | null) | Lesson;
  course?: (number | null) | Course;
  body?: string | null;
  image?: (number | null) | Media;
  consent?: boolean | null;
  teacherReply?: string | null;
  repliedAt?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "notifications".
 */
export interface Notification {
  id: number;
  portal?: (number | null) | Portal;
  user: number | User;
  title: string;
  body?: string | null;
  href?: string | null;
  read?: boolean | null;
  channel?: string | null;
  key?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "adoptions".
 */
export interface Adoption {
  id: number;
  portal?: (number | null) | Portal;
  kind: 'pack' | 'course';
  pack?: (number | null) | Pack;
  course?: (number | null) | Course;
  hidden?: boolean | null;
  order?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "placing-questions".
 */
export interface PlacingQuestion {
  id: number;
  prompt: string;
  why?: string | null;
  options:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  order?: number | null;
  portal?: (number | null) | Portal;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "placing-answers".
 */
export interface PlacingAnswer {
  id: number;
  portal?: (number | null) | Portal;
  user: number | User;
  question: number | PlacingQuestion;
  choice: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tags".
 */
export interface Tag {
  id: number;
  item:
    | {
        relationTo: 'lessons';
        value: number | Lesson;
      }
    | {
        relationTo: 'cuts';
        value: number | Cut;
      }
    | {
        relationTo: 'engagement-points';
        value: number | EngagementPoint;
      }
    | {
        relationTo: 'courses';
        value: number | Course;
      };
  clause?: (number | null) | Clause;
  seat?: (number | null) | Seat;
  state?: ('suggested' | 'confirmed') | null;
  note?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "harvest-entries".
 */
export interface HarvestEntry {
  id: number;
  portal?: (number | null) | Portal;
  user: number | User;
  lesson?: (number | null) | Lesson;
  kind?: ('quran' | 'hadith') | null;
  text?: string | null;
  reference?: string | null;
  timestamp?: string | null;
  context?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "schedules".
 */
export interface Schedule {
  id: number;
  portal?: (number | null) | Portal;
  name: string;
  owner?: (number | null) | User;
  learners?: (number | User)[] | null;
  targetType?: ('course' | 'pack') | null;
  course?: (number | null) | Course;
  pack?: (number | null) | Pack;
  startDate: string;
  endDate: string;
  weekdays:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  slots:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "events".
 */
export interface Event {
  id: number;
  portal?: (number | null) | Portal;
  title: string;
  startsAt?: string | null;
  place?: string | null;
  note?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "rsvps".
 */
export interface Rsvp {
  id: number;
  portal?: (number | null) | Portal;
  event: number | Event;
  user: number | User;
  status?: string | null;
  ticket?: string | null;
  ticketKind?: ('earned' | 'held') | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "checkins".
 */
export interface Checkin {
  id: number;
  portal?: (number | null) | Portal;
  event: number | Event;
  user: number | User;
  override?: boolean | null;
  byStaff?: (number | null) | User;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "messages".
 */
export interface Message {
  id: number;
  portal?: (number | null) | Portal;
  author?: (number | null) | User;
  body: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "completions".
 */
export interface Completion {
  id: number;
  portal?: (number | null) | Portal;
  user: number | User;
  lesson: number | Lesson;
  percent?: number | null;
  onTime?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "feedback-notes".
 */
export interface FeedbackNote {
  id: number;
  portal?: (number | null) | Portal;
  answer: number | Answer;
  author: number | User;
  second: number;
  body: string;
  audio?: (number | null) | Media;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "watch-sessions".
 */
export interface WatchSession {
  id: number;
  portal?: (number | null) | Portal;
  user: number | User;
  lesson: number | Lesson;
  seconds?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "lesson-visits".
 */
export interface LessonVisit {
  id: number;
  portal?: (number | null) | Portal;
  user: number | User;
  lesson: number | Lesson;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "seat-visits".
 */
export interface SeatVisit {
  id: number;
  portal?: (number | null) | Portal;
  user: number | User;
  seat: number | Seat;
  returned?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "rituals".
 */
export interface Ritual {
  id: number;
  portal?: (number | null) | Portal;
  user: number | User;
  note: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'portals';
        value: number | Portal;
      } | null)
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'clauses';
        value: number | Clause;
      } | null)
    | ({
        relationTo: 'seats';
        value: number | Seat;
      } | null)
    | ({
        relationTo: 'shelf-items';
        value: number | ShelfItem;
      } | null)
    | ({
        relationTo: 'courses';
        value: number | Course;
      } | null)
    | ({
        relationTo: 'units';
        value: number | Unit;
      } | null)
    | ({
        relationTo: 'lessons';
        value: number | Lesson;
      } | null)
    | ({
        relationTo: 'resources';
        value: number | Resource;
      } | null)
    | ({
        relationTo: 'packs';
        value: number | Pack;
      } | null)
    | ({
        relationTo: 'cuts';
        value: number | Cut;
      } | null)
    | ({
        relationTo: 'ladder-items';
        value: number | LadderItem;
      } | null)
    | ({
        relationTo: 'engagement-points';
        value: number | EngagementPoint;
      } | null)
    | ({
        relationTo: 'answers';
        value: number | Answer;
      } | null)
    | ({
        relationTo: 'workbook-entries';
        value: number | WorkbookEntry;
      } | null)
    | ({
        relationTo: 'notifications';
        value: number | Notification;
      } | null)
    | ({
        relationTo: 'access-codes';
        value: number | AccessCode;
      } | null)
    | ({
        relationTo: 'adoptions';
        value: number | Adoption;
      } | null)
    | ({
        relationTo: 'placing-questions';
        value: number | PlacingQuestion;
      } | null)
    | ({
        relationTo: 'placing-answers';
        value: number | PlacingAnswer;
      } | null)
    | ({
        relationTo: 'tags';
        value: number | Tag;
      } | null)
    | ({
        relationTo: 'harvest-entries';
        value: number | HarvestEntry;
      } | null)
    | ({
        relationTo: 'schedules';
        value: number | Schedule;
      } | null)
    | ({
        relationTo: 'events';
        value: number | Event;
      } | null)
    | ({
        relationTo: 'rsvps';
        value: number | Rsvp;
      } | null)
    | ({
        relationTo: 'checkins';
        value: number | Checkin;
      } | null)
    | ({
        relationTo: 'messages';
        value: number | Message;
      } | null)
    | ({
        relationTo: 'completions';
        value: number | Completion;
      } | null)
    | ({
        relationTo: 'feedback-notes';
        value: number | FeedbackNote;
      } | null)
    | ({
        relationTo: 'watch-sessions';
        value: number | WatchSession;
      } | null)
    | ({
        relationTo: 'lesson-visits';
        value: number | LessonVisit;
      } | null)
    | ({
        relationTo: 'seat-visits';
        value: number | SeatVisit;
      } | null)
    | ({
        relationTo: 'rituals';
        value: number | Ritual;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "portals_select".
 */
export interface PortalsSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  kind?: T;
  welcome?: T;
  colour?: T;
  watchHistoryOptIn?: T;
  organisationName?: T;
  description?: T;
  closed?: T;
  logoUrl?: T;
  showOthersAnswers?: T;
  notificationEmails?: T;
  theme?: T;
  calendarUrl?: T;
  learnerWelcomeUrl?: T;
  learnerIntroUrl?: T;
  teacherWelcomeUrl?: T;
  teacherIntroUrl?: T;
  learnerLabel?: T;
  teacherLabel?: T;
  wizardDone?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T;
  role?: T;
  accessCode?: T;
  extraPacks?: T;
  onboarded?: T;
  seenWelcome?: T;
  startingClause?: T;
  courseList?: T;
  extraCourses?: T;
  audience?: T;
  shareWatch?: T;
  joinedAt?: T;
  nightAlerts?: T;
  tenants?:
    | T
    | {
        tenant?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  resetPasswordRequestedAt?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  portal?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "clauses_select".
 */
export interface ClausesSelect<T extends boolean = true> {
  number?: T;
  fragment?: T;
  core?: T;
  teaching?: T;
  series?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "seats_select".
 */
export interface SeatsSelect<T extends boolean = true> {
  clause?: T;
  position?: T;
  text?: T;
  note?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "shelf-items_select".
 */
export interface ShelfItemsSelect<T extends boolean = true> {
  volume?: T;
  section?: T;
  title?: T;
  series?: T;
  empty?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "courses_select".
 */
export interface CoursesSelect<T extends boolean = true> {
  title?: T;
  summary?: T;
  speaker?: T;
  origin?: T;
  portal?: T;
  importable?: T;
  isPublic?: T;
  importToken?: T;
  hidden?: T;
  visibility?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "units_select".
 */
export interface UnitsSelect<T extends boolean = true> {
  title?: T;
  course?: T;
  order?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "lessons_select".
 */
export interface LessonsSelect<T extends boolean = true> {
  title?: T;
  unit?: T;
  course?: T;
  portal?: T;
  master?: T;
  order?: T;
  speaker?: T;
  youtubeUrl?: T;
  youtubeId?: T;
  muxAssetId?: T;
  muxPlaybackId?: T;
  durationSeconds?: T;
  transcript?: T;
  transcriptSource?: T;
  transcriptNote?: T;
  sourceUrl?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "resources_select".
 */
export interface ResourcesSelect<T extends boolean = true> {
  lesson?: T;
  name?: T;
  kind?: T;
  url?: T;
  showAtEnd?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "packs_select".
 */
export interface PacksSelect<T extends boolean = true> {
  title?: T;
  summary?: T;
  owner?: T;
  portal?: T;
  courses?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "cuts_select".
 */
export interface CutsSelect<T extends boolean = true> {
  lesson?: T;
  course?: T;
  status?: T;
  start?: T;
  end?: T;
  timestamp?: T;
  hook?: T;
  turn?: T;
  land?: T;
  fullContext?: T;
  theme?: T;
  device?: T;
  whyItAllures?: T;
  bestClause?: T;
  clauseFragment?: T;
  hangStrength?: T;
  whyHang?: T;
  seatHint?: T;
  stage2Form?: T;
  currencyNote?: T;
  quoteConfidence?: T;
  exemplarAffinity?: T;
  kind?: T;
  engine?: T;
  seat?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ladder-items_select".
 */
export interface LadderItemsSelect<T extends boolean = true> {
  lesson?: T;
  cut?: T;
  kind?: T;
  start?: T;
  end?: T;
  quote?: T;
  status?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "engagement-points_select".
 */
export interface EngagementPointsSelect<T extends boolean = true> {
  lesson?: T;
  second?: T;
  kind?: T;
  prompt?: T;
  options?: T;
  timing?: T;
  delayAmount?: T;
  delayUnit?: T;
  contingent?: T;
  link?: T;
  timeLimit?: T;
  author?: T;
  audience?: T;
  audienceUsers?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "answers_select".
 */
export interface AnswersSelect<T extends boolean = true> {
  portal?: T;
  point?: T;
  user?: T;
  lesson?: T;
  body?: T;
  choice?: T;
  image?: T;
  audio?: T;
  video?: T;
  keepPrivate?: T;
  shareWithTeacher?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "workbook-entries_select".
 */
export interface WorkbookEntriesSelect<T extends boolean = true> {
  portal?: T;
  user?: T;
  answer?: T;
  lesson?: T;
  course?: T;
  body?: T;
  image?: T;
  consent?: T;
  teacherReply?: T;
  repliedAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "notifications_select".
 */
export interface NotificationsSelect<T extends boolean = true> {
  portal?: T;
  user?: T;
  title?: T;
  body?: T;
  href?: T;
  read?: T;
  channel?: T;
  key?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "access-codes_select".
 */
export interface AccessCodesSelect<T extends boolean = true> {
  portal?: T;
  code?: T;
  role?: T;
  packs?: T;
  requiredCourses?: T;
  linkedTeacherCode?: T;
  parentMentorCode?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "adoptions_select".
 */
export interface AdoptionsSelect<T extends boolean = true> {
  portal?: T;
  kind?: T;
  pack?: T;
  course?: T;
  hidden?: T;
  order?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "placing-questions_select".
 */
export interface PlacingQuestionsSelect<T extends boolean = true> {
  prompt?: T;
  why?: T;
  options?: T;
  order?: T;
  portal?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "placing-answers_select".
 */
export interface PlacingAnswersSelect<T extends boolean = true> {
  portal?: T;
  user?: T;
  question?: T;
  choice?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tags_select".
 */
export interface TagsSelect<T extends boolean = true> {
  item?: T;
  clause?: T;
  seat?: T;
  state?: T;
  note?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "harvest-entries_select".
 */
export interface HarvestEntriesSelect<T extends boolean = true> {
  portal?: T;
  user?: T;
  lesson?: T;
  kind?: T;
  text?: T;
  reference?: T;
  timestamp?: T;
  context?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "schedules_select".
 */
export interface SchedulesSelect<T extends boolean = true> {
  portal?: T;
  name?: T;
  owner?: T;
  learners?: T;
  targetType?: T;
  course?: T;
  pack?: T;
  startDate?: T;
  endDate?: T;
  weekdays?: T;
  slots?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "events_select".
 */
export interface EventsSelect<T extends boolean = true> {
  portal?: T;
  title?: T;
  startsAt?: T;
  place?: T;
  note?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "rsvps_select".
 */
export interface RsvpsSelect<T extends boolean = true> {
  portal?: T;
  event?: T;
  user?: T;
  status?: T;
  ticket?: T;
  ticketKind?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "checkins_select".
 */
export interface CheckinsSelect<T extends boolean = true> {
  portal?: T;
  event?: T;
  user?: T;
  override?: T;
  byStaff?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "messages_select".
 */
export interface MessagesSelect<T extends boolean = true> {
  portal?: T;
  author?: T;
  body?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "completions_select".
 */
export interface CompletionsSelect<T extends boolean = true> {
  portal?: T;
  user?: T;
  lesson?: T;
  percent?: T;
  onTime?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "feedback-notes_select".
 */
export interface FeedbackNotesSelect<T extends boolean = true> {
  portal?: T;
  answer?: T;
  author?: T;
  second?: T;
  body?: T;
  audio?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "watch-sessions_select".
 */
export interface WatchSessionsSelect<T extends boolean = true> {
  portal?: T;
  user?: T;
  lesson?: T;
  seconds?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "lesson-visits_select".
 */
export interface LessonVisitsSelect<T extends boolean = true> {
  portal?: T;
  user?: T;
  lesson?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "seat-visits_select".
 */
export interface SeatVisitsSelect<T extends boolean = true> {
  portal?: T;
  user?: T;
  seat?: T;
  returned?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "rituals_select".
 */
export interface RitualsSelect<T extends boolean = true> {
  portal?: T;
  user?: T;
  note?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}