/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    portals: Portal;
    users: User;
    media: Media;
    clauses: Clause;
    doors: Door;
    seats: Seat;
    'shelf-items': ShelfItem;
    speakers: Speaker;
    courses: Course;
    units: Unit;
    lessons: Lesson;
    resources: Resource;
    packs: Pack;
    cuts: Cut;
    'ladder-items': LadderItem;
    'engagement-points': EngagementPoint;
    answers: Answer;
    'workbook-entries': WorkbookEntry;
    notifications: Notification;
    'access-codes': AccessCode;
    'talk-tiers': TalkTier;
    adoptions: Adoption;
    'placing-questions': PlacingQuestion;
    'placing-answers': PlacingAnswer;
    tags: Tag;
    'harvest-entries': HarvestEntry;
    'drawn-to': DrawnTo;
    schedules: Schedule;
    events: Event;
    rsvps: Rsvp;
    checkins: Checkin;
    messages: Message;
    completions: Completion;
    'feedback-notes': FeedbackNote;
    'watch-sessions': WatchSession;
    'lesson-visits': LessonVisit;
    'seat-visits': SeatVisit;
    rituals: Ritual;
    'circle-answers': CircleAnswer;
    'feedback-summaries': FeedbackSummary;
    'question-rewrites': QuestionRewrite;
    'scripture-cache': ScriptureCache;
    'heart-scales': HeartScale;
    lanes: Lane;
    'opening-scenes': OpeningScene;
    'opening-configs': OpeningConfig;
    'heart-states': HeartState;
    'opening-answers': OpeningAnswer;
    'heart-contributions': HeartContribution;
    'view-as-sessions': ViewAsSession;
    'audit-log': AuditLog;
    'persona-bands': PersonaBand;
    'compass-settings': CompassSetting;
    'compass-attempts': CompassAttempt;
    'compass-mixes': CompassMix;
    'compass-serves': CompassServe;
    'ai-steps': AiStep;
    'ai-step-versions': AiStepVersion;
    'ai-step-outputs': AiStepOutput;
    'ai-step-jobs': AiStepJob;
    'ai-desk': AiDesk;
    'sheet-keys': SheetKey;
    'sheet-imports': SheetImport;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    portals: PortalsSelect<false> | PortalsSelect<true>;
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    clauses: ClausesSelect<false> | ClausesSelect<true>;
    doors: DoorsSelect<false> | DoorsSelect<true>;
    seats: SeatsSelect<false> | SeatsSelect<true>;
    'shelf-items': ShelfItemsSelect<false> | ShelfItemsSelect<true>;
    speakers: SpeakersSelect<false> | SpeakersSelect<true>;
    courses: CoursesSelect<false> | CoursesSelect<true>;
    units: UnitsSelect<false> | UnitsSelect<true>;
    lessons: LessonsSelect<false> | LessonsSelect<true>;
    resources: ResourcesSelect<false> | ResourcesSelect<true>;
    packs: PacksSelect<false> | PacksSelect<true>;
    cuts: CutsSelect<false> | CutsSelect<true>;
    'ladder-items': LadderItemsSelect<false> | LadderItemsSelect<true>;
    'engagement-points': EngagementPointsSelect<false> | EngagementPointsSelect<true>;
    answers: AnswersSelect<false> | AnswersSelect<true>;
    'workbook-entries': WorkbookEntriesSelect<false> | WorkbookEntriesSelect<true>;
    notifications: NotificationsSelect<false> | NotificationsSelect<true>;
    'access-codes': AccessCodesSelect<false> | AccessCodesSelect<true>;
    'talk-tiers': TalkTiersSelect<false> | TalkTiersSelect<true>;
    adoptions: AdoptionsSelect<false> | AdoptionsSelect<true>;
    'placing-questions': PlacingQuestionsSelect<false> | PlacingQuestionsSelect<true>;
    'placing-answers': PlacingAnswersSelect<false> | PlacingAnswersSelect<true>;
    tags: TagsSelect<false> | TagsSelect<true>;
    'harvest-entries': HarvestEntriesSelect<false> | HarvestEntriesSelect<true>;
    'drawn-to': DrawnToSelect<false> | DrawnToSelect<true>;
    schedules: SchedulesSelect<false> | SchedulesSelect<true>;
    events: EventsSelect<false> | EventsSelect<true>;
    rsvps: RsvpsSelect<false> | RsvpsSelect<true>;
    checkins: CheckinsSelect<false> | CheckinsSelect<true>;
    messages: MessagesSelect<false> | MessagesSelect<true>;
    completions: CompletionsSelect<false> | CompletionsSelect<true>;
    'feedback-notes': FeedbackNotesSelect<false> | FeedbackNotesSelect<true>;
    'watch-sessions': WatchSessionsSelect<false> | WatchSessionsSelect<true>;
    'lesson-visits': LessonVisitsSelect<false> | LessonVisitsSelect<true>;
    'seat-visits': SeatVisitsSelect<false> | SeatVisitsSelect<true>;
    rituals: RitualsSelect<false> | RitualsSelect<true>;
    'circle-answers': CircleAnswersSelect<false> | CircleAnswersSelect<true>;
    'feedback-summaries': FeedbackSummariesSelect<false> | FeedbackSummariesSelect<true>;
    'question-rewrites': QuestionRewritesSelect<false> | QuestionRewritesSelect<true>;
    'scripture-cache': ScriptureCacheSelect<false> | ScriptureCacheSelect<true>;
    'heart-scales': HeartScalesSelect<false> | HeartScalesSelect<true>;
    lanes: LanesSelect<false> | LanesSelect<true>;
    'opening-scenes': OpeningScenesSelect<false> | OpeningScenesSelect<true>;
    'opening-configs': OpeningConfigsSelect<false> | OpeningConfigsSelect<true>;
    'heart-states': HeartStatesSelect<false> | HeartStatesSelect<true>;
    'opening-answers': OpeningAnswersSelect<false> | OpeningAnswersSelect<true>;
    'heart-contributions': HeartContributionsSelect<false> | HeartContributionsSelect<true>;
    'view-as-sessions': ViewAsSessionsSelect<false> | ViewAsSessionsSelect<true>;
    'audit-log': AuditLogSelect<false> | AuditLogSelect<true>;
    'persona-bands': PersonaBandsSelect<false> | PersonaBandsSelect<true>;
    'compass-settings': CompassSettingsSelect<false> | CompassSettingsSelect<true>;
    'compass-attempts': CompassAttemptsSelect<false> | CompassAttemptsSelect<true>;
    'compass-mixes': CompassMixesSelect<false> | CompassMixesSelect<true>;
    'compass-serves': CompassServesSelect<false> | CompassServesSelect<true>;
    'ai-steps': AiStepsSelect<false> | AiStepsSelect<true>;
    'ai-step-versions': AiStepVersionsSelect<false> | AiStepVersionsSelect<true>;
    'ai-step-outputs': AiStepOutputsSelect<false> | AiStepOutputsSelect<true>;
    'ai-step-jobs': AiStepJobsSelect<false> | AiStepJobsSelect<true>;
    'ai-desk': AiDeskSelect<false> | AiDeskSelect<true>;
    'sheet-keys': SheetKeysSelect<false> | SheetKeysSelect<true>;
    'sheet-imports': SheetImportsSelect<false> | SheetImportsSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {
    'master-flags': MasterFlag;
  };
  globalsSelect: {
    'master-flags': MasterFlagsSelect<false> | MasterFlagsSelect<true>;
  };
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "portals".
 */
export interface Portal {
  id: number;
  name: string;
  slug: string;
  kind?: ('mosque' | 'church' | 'synagogue' | 'other') | null;
  welcome?: string | null;
  colour?: string | null;
  watchHistoryOptIn?: boolean | null;
  organisationName?: string | null;
  description?: string | null;
  closed?: boolean | null;
  logoUrl?: string | null;
  showOthersAnswers?: boolean | null;
  notificationEmails?: string | null;
  theme?: ('light' | 'dark') | null;
  calendarUrl?: string | null;
  learnerWelcomeUrl?: string | null;
  learnerIntroUrl?: string | null;
  teacherWelcomeUrl?: string | null;
  teacherIntroUrl?: string | null;
  learnerLabel?: string | null;
  teacherLabel?: string | null;
  wizardDone?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  name: string;
  role: 'master' | 'portal-admin' | 'teacher' | 'learner';
  accessCode?: (number | null) | AccessCode;
  extraPacks?: (number | Pack)[] | null;
  onboarded?: boolean | null;
  seenWelcome?: boolean | null;
  startingClause?: number | null;
  courseList?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  extraCourses?: (number | Course)[] | null;
  audience?: string | null;
  shareWatch?: boolean | null;
  joinedAt?: string | null;
  nightAlerts?: boolean | null;
  shareOpening?: boolean | null;
  keepPlace?: boolean | null;
  trendsOptIn?: boolean | null;
  shareWithLearners?: boolean | null;
  haptics?: boolean | null;
  removed?: boolean | null;
  updatedBy?: (number | null) | User;
  onBehalfOf?: (number | null) | User;
  tenants?:
    | {
        tenant: number | Portal;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  resetPasswordRequestedAt?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "access-codes".
 */
export interface AccessCode {
  id: number;
  portal?: (number | null) | Portal;
  code: string;
  role: 'learner' | 'teacher' | 'admin' | 'parent';
  packs?: (number | Pack)[] | null;
  requiredCourses?: (number | Course)[] | null;
  linkedTeacherCode?: (number | null) | AccessCode;
  parentMentorCode?: (number | null) | AccessCode;
  /**
   * A name for the desk, so codes can be found without printing them.
   */
  label?: string | null;
  /**
   * After this moment the code stops working.
   */
  expiresAt?: string | null;
  /**
   * Leave empty for no limit.
   */
  maxUses?: number | null;
  uses?: number | null;
  disabled?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "packs".
 */
export interface Pack {
  id: number;
  title: string;
  summary?: string | null;
  owner: 'master' | 'portal';
  portal?: (number | null) | Portal;
  courses?: (number | Course)[] | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "courses".
 */
export interface Course {
  id: number;
  title: string;
  summary?: string | null;
  speaker?: string | null;
  speakerProfile?: (number | null) | Speaker;
  origin: 'master' | 'local';
  portal?: (number | null) | Portal;
  importable?: boolean | null;
  isPublic?: boolean | null;
  importToken?: string | null;
  hidden?: boolean | null;
  visibility?: ('draft' | 'published') | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "speakers".
 */
export interface Speaker {
  id: number;
  name: string;
  honorific?: string | null;
  displayName?: string | null;
  slug: string;
  /**
   * Other ways this speaker is named, so an import maps them here.
   */
  aliases?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  bio?: string | null;
  photo?: (number | null) | Media;
  /**
   * An https address of an image, when the photo is not an upload.
   */
  photoUrl?: string | null;
  /**
   * Where the photo was found, when it is not an image address.
   */
  photoSource?: string | null;
  /**
   * [{ "label": "Site", "url": "https://…" }]
   */
  links?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  sources?: string | null;
  status?: ('draft' | 'published') | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  alt?: string | null;
  portal?: (number | null) | Portal;
  prefix?: string | null;
  _objectKey?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "clauses".
 */
export interface Clause {
  id: number;
  number: number;
  fragment: string;
  core?: string | null;
  teaching?: string | null;
  series?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * The 20 working doors learners see. Each absorbs one or more of the 41 clauses; a talk’s door comes from its clause.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "doors".
 */
export interface Door {
  id: number;
  number: number;
  section: 'Sitting' | 'Islam' | 'Iman' | 'Ihsan' | 'Hour' | 'Trunk';
  title: string;
  /**
   * The clause numbers this door absorbs, for example [13, 19, 20].
   */
  clauses:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "seats".
 */
export interface Seat {
  id: number;
  clause: number | Clause;
  position: number;
  text: string;
  note?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "shelf-items".
 */
export interface ShelfItem {
  id: number;
  volume?: string | null;
  section?: string | null;
  title: string;
  series?: string | null;
  empty?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "units".
 */
export interface Unit {
  id: number;
  title: string;
  course: number | Course;
  order?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "lessons".
 */
export interface Lesson {
  id: number;
  title: string;
  unit: number | Unit;
  course: number | Course;
  portal?: (number | null) | Portal;
  master?: boolean | null;
  order?: number | null;
  speaker?: string | null;
  speakerProfile?: (number | null) | Speaker;
  youtubeUrl?: string | null;
  youtubeId?: string | null;
  videoProvider?: ('youtube' | 'vimeo' | 'file') | null;
  vimeoId?: string | null;
  film?: (number | null) | Media;
  /**
   * Mux-ready. Unused until a Mux asset is attached.
   */
  muxAssetId?: string | null;
  muxPlaybackId?: string | null;
  durationSeconds?: number | null;
  transcript?: string | null;
  transcriptSource?: ('none' | 'youtube' | 'upload' | 'pending') | null;
  transcriptNote?: string | null;
  sourceUrl?: string | null;
  /**
   * Seq in HEARTS-8k-LINKS-for-bots.csv, for audit.
   */
  csvSeq?: number | null;
  starterLane?: string | null;
  /**
   * The title exactly as YouTube and the links list have it.
   */
  sourceTitle?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "resources".
 */
export interface Resource {
  id: number;
  lesson: number | Lesson;
  name: string;
  kind?: ('link' | 'file' | 'summary' | 'quote' | 'reading' | 'guide' | 'transcript') | null;
  url?: string | null;
  /**
   * An uploaded file. A transcript row uses this instead of pasting the words into a cell.
   */
  file?: (number | null) | Media;
  body?: string | null;
  showAtEnd?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "cuts".
 */
export interface Cut {
  id: number;
  lesson: number | Lesson;
  course?: (number | null) | Course;
  status?: ('draft' | 'suggested' | 'approved' | 'rejected') | null;
  /**
   * A 0:00 to 0:20 stand-in until the cutting pass sets real in and out points.
   */
  placeholder?: boolean | null;
  presentation?: ('video' | 'slide') | null;
  playable?: boolean | null;
  lastError?: string | null;
  start: number;
  end: number;
  timestamp?: string | null;
  hook: string;
  turn: string;
  land: string;
  fullContext?: string | null;
  theme?: string | null;
  device?: string | null;
  whyItAllures?: string | null;
  bestClause?: number | null;
  clauseFragment?: string | null;
  hangStrength?: string | null;
  whyHang?: string | null;
  seatHint?: string | null;
  stage2Form?: string | null;
  currencyNote?: string | null;
  quoteConfidence?: string | null;
  exemplarAffinity?: string | null;
  kind?: string | null;
  engine?: string | null;
  seat?: (number | null) | Seat;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ladder-items".
 */
export interface LadderItem {
  id: number;
  lesson: number | Lesson;
  cut?: (number | null) | Cut;
  kind?: ('hors' | 'appetiser') | null;
  start?: number | null;
  end?: number | null;
  quote?: string | null;
  /**
   * This piece's own parent. An appetiser points at its full talk (talk:<lesson id>). A hors d'oeuvre points at its appetiser (appetiser:<id>), never straight at the talk.
   */
  parentRef?: string | null;
  status?: ('draft' | 'approved' | 'rejected') | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "engagement-points".
 */
export interface EngagementPoint {
  id: number;
  lesson: number | Lesson;
  cut?: (number | null) | Cut;
  /**
   * Only timestamps for now. Other ways to set when a question appears can be added here.
   */
  triggerType?: 'timestamp' | null;
  /**
   * Seconds into the source film (so the same question fires in the Hors and the Appetiser).
   */
  second: number;
  /**
   * Check-in nudges: [{ "option": "...", "scale": "belonging", "delta": -1 }]
   */
  nudges?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  crisisOption?: string | null;
  /**
   * For multiple choice: the option that is right, if any. Shown only after answering.
   */
  correctOption?: string | null;
  timeLimitSec?: number | null;
  kind?: ('question' | 'multiple_choice' | 'reflection' | 'task') | null;
  prompt: string;
  options?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  timing?: ('immediate' | 'future') | null;
  delayAmount?: number | null;
  delayUnit?: ('second' | 'minute' | 'hour' | 'day' | 'week') | null;
  contingent?: (number | null) | EngagementPoint;
  link?: string | null;
  timeLimit?: number | null;
  author?: (number | null) | User;
  audience?: ('everyone' | 'self' | 'selected') | null;
  audienceUsers?: (number | User)[] | null;
  /**
   * Learners only see published pop-ups. Drafts from the transcript wait here for a person.
   */
  status?: ('published' | 'draft' | 'rejected') | null;
  draftNote?: string | null;
  reviewedBy?: (number | null) | User;
  family?: ('popup' | 'workbook' | 'task') | null;
  /**
   * Activation tasks: days the learner has, counted from when they first open the talk.
   */
  dueDays?: number | null;
  evidence?: ('none' | 'note' | 'photo') | null;
  /**
   * When set, the learner’s answer is visible to their imam and the portal admin.
   */
  showImam?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "answers".
 */
export interface Answer {
  id: number;
  portal?: (number | null) | Portal;
  point: number | EngagementPoint;
  user: number | User;
  lesson?: (number | null) | Lesson;
  body?: string | null;
  choice?: string | null;
  image?: (number | null) | Media;
  audio?: (number | null) | Media;
  video?: (number | null) | Media;
  keepPrivate?: boolean | null;
  shareWithTeacher?: boolean | null;
  /**
   * The learner chose to let other learners on this video read it. Separate from sharing with their teacher.
   */
  shareWithLearners?: boolean | null;
  cut?: (number | null) | Cut;
  atSecond?: number | null;
  viewingId?: string | null;
  answeredAt?: string | null;
  pendingSync?: boolean | null;
  correct?: boolean | null;
  /**
   * Questions on a hors d'oeuvre or appetiser do not count toward the grow page. Only questions on a full talk do.
   */
  sourceLevel?: ('talk' | 'hors' | 'appetiser') | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "workbook-entries".
 */
export interface WorkbookEntry {
  id: number;
  portal?: (number | null) | Portal;
  user: number | User;
  answer?: (number | null) | Answer;
  lesson?: (number | null) | Lesson;
  course?: (number | null) | Course;
  body?: string | null;
  image?: (number | null) | Media;
  consent?: boolean | null;
  teacherReply?: string | null;
  repliedAt?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "notifications".
 */
export interface Notification {
  id: number;
  portal?: (number | null) | Portal;
  user: number | User;
  title: string;
  body?: string | null;
  href?: string | null;
  read?: boolean | null;
  channel?: string | null;
  key?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "talk-tiers".
 */
export interface TalkTier {
  id: number;
  lesson: number | Lesson;
  horsStart: number;
  horsEnd: number;
  horsQuote?: string | null;
  appetiserStart: number;
  appetiserEnd: number;
  hook?: string | null;
  turn?: string | null;
  land?: string | null;
  /**
   * When the hook is said, for the appetiser captions.
   */
  hookAt?: number | null;
  turnAt?: number | null;
  landAt?: number | null;
  /**
   * Up to three appetiser cuts, played hook then turn then land: [{ role, start, end }]. Their lengths add up to at most about 3 minutes.
   */
  appetiserSpans?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  /**
   * The hors d'oeuvre's sentences with their times: [{ at, text }]. text is the raw caption, kept for timing.
   */
  horsLines?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  /**
   * Tidied learner-facing lines. Raw captions stay on horsQuote, hook, turn, land and horsLines. Shape: { version, source, quote, hook, turn, land, horsLines: [{ at, raw, text }] }.
   */
  lineTidy?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  /**
   * The typography style that can stand in for the hors d'oeuvre clip.
   */
  typographyStyle?: ('kinetic' | 'windows' | 'conversation' | 'cinema' | 'unfold') | null;
  /**
   * Typography in place of the clip. Learners see the rendered video instead of the hors d'oeuvre.
   */
  typographyInPlace?: boolean | null;
  /**
   * Offer "Resume from where the appetiser ended" next to the main, which always opens at 0:00.
   */
  offerResume?: boolean | null;
  status?: ('draft' | 'checked' | 'rejected') | null;
  checkedAt?: string | null;
  /**
   * Where the draft came from, for example the caption file.
   */
  source?: string | null;
  note?: string | null;
  checkedBy?: (number | null) | User;
  /**
   * hors d'oeuvre -> its appetiser -> its full talk. Written on every save from the lesson this tier belongs to.
   */
  parents?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "adoptions".
 */
export interface Adoption {
  id: number;
  portal?: (number | null) | Portal;
  kind: 'pack' | 'course';
  pack?: (number | null) | Pack;
  course?: (number | null) | Course;
  hidden?: boolean | null;
  order?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "placing-questions".
 */
export interface PlacingQuestion {
  id: number;
  prompt: string;
  why?: string | null;
  options:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  order?: number | null;
  portal?: (number | null) | Portal;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "placing-answers".
 */
export interface PlacingAnswer {
  id: number;
  portal?: (number | null) | Portal;
  user: number | User;
  question: number | PlacingQuestion;
  choice: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tags".
 */
export interface Tag {
  id: number;
  item:
    | {
        relationTo: 'lessons';
        value: number | Lesson;
      }
    | {
        relationTo: 'cuts';
        value: number | Cut;
      }
    | {
        relationTo: 'engagement-points';
        value: number | EngagementPoint;
      }
    | {
        relationTo: 'courses';
        value: number | Course;
      };
  clause?: (number | null) | Clause;
  seat?: (number | null) | Seat;
  lane?: (number | null) | Lane;
  /**
   * The heart scale this talk serves. The compass steers with it.
   */
  scale?: (number | null) | HeartScale;
  weight?: number | null;
  state?: ('suggested' | 'confirmed') | null;
  note?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "lanes".
 */
export interface Lane {
  id: number;
  key: string;
  title: string;
  scale?: (number | null) | HeartScale;
  fit?: ('natural' | 'workable' | 'weak') | null;
  clauses?:
    | {
        clause: number | Clause;
        rank: number;
        id?: string | null;
      }[]
    | null;
  seats?: (number | Seat)[] | null;
  seriesNote?: string | null;
  optInOnly?: boolean | null;
  /**
   * Never served in this lane during a learner’s first 7 days.
   */
  excludeClauses?: (number | Clause)[] | null;
  order?: number | null;
  reachPhrase?: string | null;
  /**
   * The default lane behind “Just show me something”. Never scored or shown.
   */
  pseudo?: boolean | null;
  starters?:
    | {
        lesson: number | Lesson;
        role: 'first' | 'next' | 'mains';
        order?: number | null;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "heart-scales".
 */
export interface HeartScale {
  id: number;
  key:
    'desire' | 'greed' | 'anger' | 'ego' | 'worry' | 'belonging' | 'gratitude' | 'faith' | 'compassion' | 'discipline';
  leonName: string;
  room?: ('appetites' | 'heat' | 'unsettled' | 'lights') | null;
  polishLabel?: string | null;
  /**
   * The short word in “Focusing on”. Learners see this, never the desk name.
   */
  focusName?: string | null;
  season?: ('youth' | 'health' | 'wealth' | 'freeTime' | 'life') | null;
  firstOpenRead?: boolean | null;
  /**
   * Leon’s rung texts, for authors only.
   */
  anchors?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "harvest-entries".
 */
export interface HarvestEntry {
  id: number;
  portal?: (number | null) | Portal;
  user: number | User;
  lesson?: (number | null) | Lesson;
  kind?: ('quran' | 'hadith' | 'line') | null;
  text?: string | null;
  reference?: string | null;
  timestamp?: string | null;
  context?: string | null;
  /**
   * Where the quote starts in the talk. Harvest replays from a few seconds before.
   */
  seconds?: number | null;
  /**
   * Set only when the speaker’s words matched the Qur’an text clearly.
   */
  surah?: number | null;
  ayah?: number | null;
  /**
   * arabic, transliteration or english: how the quote was recognised.
   */
  matchedBy?: string | null;
  /**
   * Hadith collection the speaker named, when a hadith in it matched clearly.
   */
  collection?: string | null;
  hadithNumber?: string | null;
  hadithText?: string | null;
  hadithArabic?: string | null;
  /**
   * Only as given by the hadith source. Never filled in by hand.
   */
  grading?: string | null;
  /**
   * When the learner first opened Harvest with this item in it. Empty means new.
   */
  seenAt?: string | null;
  speaker?: string | null;
  /**
   * The Hadith Jibril working door (1 to 20) of the talk, worked out from its clause.
   */
  door?: number | null;
  /**
   * Where it was kept. A short clip fills the harvest only; it never counts towards progress.
   */
  surface?: ('hors' | 'appetiser' | 'talk') | null;
  gatheredAt?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "drawn-to".
 */
export interface DrawnTo {
  id: number;
  portal?: (number | null) | Portal;
  user: number | User;
  speaker: string;
  speakerSlug: string;
  linger?: number | null;
  learnMore?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "schedules".
 */
export interface Schedule {
  id: number;
  portal?: (number | null) | Portal;
  name: string;
  owner?: (number | null) | User;
  learners?: (number | User)[] | null;
  targetType?: ('course' | 'pack') | null;
  course?: (number | null) | Course;
  pack?: (number | null) | Pack;
  startDate: string;
  endDate: string;
  weekdays:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  slots:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "events".
 */
export interface Event {
  id: number;
  portal?: (number | null) | Portal;
  title: string;
  startsAt?: string | null;
  place?: string | null;
  note?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "rsvps".
 */
export interface Rsvp {
  id: number;
  portal?: (number | null) | Portal;
  event: number | Event;
  user: number | User;
  status?: string | null;
  ticket?: string | null;
  ticketKind?: ('earned' | 'held') | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "checkins".
 */
export interface Checkin {
  id: number;
  portal?: (number | null) | Portal;
  event: number | Event;
  user: number | User;
  override?: boolean | null;
  byStaff?: (number | null) | User;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "messages".
 */
export interface Message {
  id: number;
  portal?: (number | null) | Portal;
  author?: (number | null) | User;
  body: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "completions".
 */
export interface Completion {
  id: number;
  portal?: (number | null) | Portal;
  user: number | User;
  lesson: number | Lesson;
  percent?: number | null;
  onTime?: boolean | null;
  /**
   * Only a full talk inside a course counts toward completion and the grow page.
   */
  sourceLevel?: ('talk' | 'hors' | 'appetiser') | null;
  /**
   * When the learner watched this, if that is not the row time. The compass uses it.
   */
  watchedAt?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "feedback-notes".
 */
export interface FeedbackNote {
  id: number;
  portal?: (number | null) | Portal;
  answer: number | Answer;
  author: number | User;
  second: number;
  body: string;
  audio?: (number | null) | Media;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "watch-sessions".
 */
export interface WatchSession {
  id: number;
  portal?: (number | null) | Portal;
  user: number | User;
  lesson: number | Lesson;
  seconds?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "lesson-visits".
 */
export interface LessonVisit {
  id: number;
  portal?: (number | null) | Portal;
  user: number | User;
  lesson: number | Lesson;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "seat-visits".
 */
export interface SeatVisit {
  id: number;
  portal?: (number | null) | Portal;
  user: number | User;
  seat: number | Seat;
  returned?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "rituals".
 */
export interface Ritual {
  id: number;
  portal?: (number | null) | Portal;
  user: number | User;
  note: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * Shown in the swarm with the circle label. Never counted in analytics, trends, profiles or progress.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "circle-answers".
 */
export interface CircleAnswer {
  id: number;
  point: number | EngagementPoint;
  lesson?: (number | null) | Lesson;
  /**
   * Empty: every portal with this question. Set: that portal only.
   */
  portal?: (number | null) | Portal;
  name: string;
  body: string;
  tone?: string | null;
  length?: string | null;
  origin?: ('ai' | 'staff') | null;
  enabled?: boolean | null;
  author?: (number | null) | User;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "feedback-summaries".
 */
export interface FeedbackSummary {
  id: number;
  portal?: (number | null) | Portal;
  point?: (number | null) | EngagementPoint;
  questionKey?: string | null;
  themes:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  quotes:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  status?: ('draft' | 'included') | null;
  stepSlug?: string | null;
  versionNumber?: number | null;
  author?: (number | null) | User;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "question-rewrites".
 */
export interface QuestionRewrite {
  id: number;
  point: number | EngagementPoint;
  prompt: string;
  talk?: string | null;
  family?: string | null;
  reasons:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  rewrite: string;
  status?: 'draft' | null;
  author?: (number | null) | User;
  updatedAt: string;
  createdAt: string;
}
/**
 * Tafsir, hadith and summaries fetched from open sources, kept so each is fetched once.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "scripture-cache".
 */
export interface ScriptureCache {
  id: number;
  key: string;
  kind?: string | null;
  data?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "opening-scenes".
 */
export interface OpeningScene {
  id: number;
  key: string;
  order?: number | null;
  /**
   * Mark one word with **double stars** to emphasise it.
   */
  caption: string;
  subline?: string | null;
  scene?: (number | null) | Media;
  layout?: ('grid4' | 'bubbles' | 'doorsCarousel') | null;
  options?:
    | {
        key: string;
        label: string;
        replyPill?: string | null;
        nudges?:
          | {
              scale:
                | 'desire'
                | 'greed'
                | 'anger'
                | 'ego'
                | 'worry'
                | 'belonging'
                | 'gratitude'
                | 'faith'
                | 'compassion'
                | 'discipline';
              delta?: number | null;
              id?: string | null;
            }[]
          | null;
        intentLane?: (number | null) | Lane;
        spineFirst?: boolean | null;
        crisis?: boolean | null;
        sensitivity?: ('normal' | 'private') | null;
        id?: string | null;
      }[]
    | null;
  status?: ('draft' | 'published') | null;
  version?: number | null;
  adaptedFrom?: string | null;
  /**
   * Wording for the monthly look. Same options, different words.
   */
  monthCaption?: string | null;
  monthSubline?: string | null;
  /**
   * Option key to this month’s label.
   */
  monthLabels?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "opening-configs".
 */
export interface OpeningConfig {
  id: number;
  /**
   * Empty for the master default.
   */
  portal?: (number | null) | Portal;
  wording?:
    | {
        scene: number | OpeningScene;
        caption?: string | null;
        subline?: string | null;
        labels?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        id?: string | null;
      }[]
    | null;
  hiddenScenes?: (number | OpeningScene)[] | null;
  defaultClip?: (number | null) | Cut;
  helpContacts?:
    | {
        label: string;
        phone?: string | null;
        url?: string | null;
        hours?: string | null;
        id?: string | null;
      }[]
    | null;
  trendsContributionPrompt?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "heart-states".
 */
export interface HeartState {
  id: number;
  user: number | User;
  state:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "opening-answers".
 */
export interface OpeningAnswer {
  id: number;
  user: number | User;
  portal?: (number | null) | Portal;
  scene?: (number | null) | OpeningScene;
  sceneKey: string;
  /**
   * The option key, or pass, or not-reached.
   */
  optionKey: string;
  labelSnapshot?: string | null;
  private?: boolean | null;
  /**
   * Set by the server: not private, and the learner shares opening answers with their mentor.
   */
  staffVisible?: boolean | null;
  mentors?: (number | User)[] | null;
  scenesVersion?: number | null;
  answeredAt?: string | null;
  recordedAt?: string | null;
  supersededAt?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "heart-contributions".
 */
export interface HeartContribution {
  id: number;
  portal: number | Portal;
  isoWeek: string;
  doorKey?: string | null;
  scenePasses?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  laneTop2?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  nonceHash?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "view-as-sessions".
 */
export interface ViewAsSession {
  id: number;
  actor: number | User;
  actorRole?: string | null;
  target: number | User;
  targetRole?: string | null;
  portal?: (number | null) | Portal;
  reason: string;
  token?: string | null;
  startedAt?: string | null;
  lastSeenAt?: string | null;
  expiresAt?: string | null;
  endedAt?: string | null;
  endReason?:
    | (
        | 'exit'
        | 'idle-timeout'
        | 'max-timeout'
        | 'replaced'
        | 'actor-signed-out'
        | 'role-changed'
        | 'target-removed'
        | 'portal-closed'
      )
    | null;
  writeEnabled?: boolean | null;
  writeUntil?: string | null;
  returnTo?: string | null;
  ipHash?: string | null;
  userAgent?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "audit-log".
 */
export interface AuditLog {
  id: number;
  event: string;
  actor?: (number | null) | User;
  actorRole?: string | null;
  target?: (number | null) | User;
  targetRole?: string | null;
  portal?: (number | null) | Portal;
  sessionId?: string | null;
  reason?: string | null;
  at: string;
  ipHash?: string | null;
  detail?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Master-only rough guide. Drafts are not counted. A persona is never stored on a learner.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "persona-bands".
 */
export interface PersonaBand {
  id: number;
  key: string;
  title: string;
  status?: ('draft' | 'published') | null;
  source?: ('unassigned' | 'doc-a' | 'doc-b' | 'doc-c' | 'ux-draft' | 'balanced') | null;
  /**
   * Stand-in numbers. Publishing stays closed while this is ticked.
   */
  placeholder?: boolean | null;
  /**
   * Bands that arrived with the same ranges share a group name.
   */
  identicalGroup?: string | null;
  note?: string | null;
  /**
   * 2 is the balanced reading in PERSONA-BALANCING.md.
   */
  version?: number | null;
  description?: string | null;
  /**
   * Working doors, 1 to 20, that this band leans on.
   */
  doors?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  /**
   * Talk titles to lean on. Staff only.
   */
  talks?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  ranges?:
    | {
        scale:
          | 'desire'
          | 'greed'
          | 'anger'
          | 'ego'
          | 'worry'
          | 'belonging'
          | 'gratitude'
          | 'faith'
          | 'compassion'
          | 'discipline';
        /**
         * Unticked: the source table has no row for this scale.
         */
        present?: boolean | null;
        min?: number | null;
        max?: number | null;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * The warm words a learner sees. The rung bounds stay on this desk.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "compass-settings".
 */
export interface CompassSetting {
  id: number;
  key: string;
  frame?: ('both' | 'focusing' | 'places') | null;
  focusLead?: string | null;
  movementUp?: string | null;
  movementSame?: string | null;
  movementOnward?: string | null;
  lifeCaption?: string | null;
  lifeSubline?: string | null;
  places?:
    | {
        key?: ('growing' | 'steady' | 'flourishing') | null;
        label: string;
        low?: number | null;
        high?: number | null;
        forward?: string | null;
        id?: string | null;
      }[]
    | null;
  lifeOptions?:
    | {
        key: string;
        label: string;
        boost?:
          | (
              | 'desire'
              | 'greed'
              | 'anger'
              | 'ego'
              | 'worry'
              | 'belonging'
              | 'gratitude'
              | 'faith'
              | 'compassion'
              | 'discipline'
            )
          | null;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Each opening and each monthly look. The signed readings are for the portal admin, the imam and the master.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "compass-attempts".
 */
export interface CompassAttempt {
  id: number;
  user: number | User;
  portal: number | Portal;
  at: string;
  bank?: ('opening' | 'month') | null;
  lifeKey?: string | null;
  /**
   * Every life line ticked this round. History is append-only.
   */
  lifeKeys?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  lifeNote?: string | null;
  formKey?: string | null;
  demoKey?: string | null;
  /**
   * Device readings from −1 to +1. Not shown to the learner.
   */
  scales?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * How this portal splits the shelf between quieter scales, steady ones, and a door not sat with lately.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "compass-mixes".
 */
export interface CompassMix {
  id: number;
  portal: number | Portal;
  deficit?: number | null;
  strength?: number | null;
  discovery?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * A talk the compass put forward, and why. Learners do not see the why.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "compass-serves".
 */
export interface CompassServe {
  id: number;
  user: number | User;
  portal: number | Portal;
  lesson?: (number | null) | Lesson;
  title: string;
  kind?: ('hors' | 'appetiser' | 'course' | 'talk') | null;
  why?: string | null;
  mix?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  at: string;
  door?: number | null;
  bucket?: string | null;
  demoKey?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ai-steps".
 */
export interface AiStep {
  id: number;
  slug: string;
  name: string;
  description: string;
  placeholders:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  prompt: string;
  provider?: ('anthropic' | 'openai') | null;
  model?: string | null;
  temperature?: number | null;
  maxTokens?: number | null;
  outputSchema?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  fills?: string | null;
  pipelineOrder?: number | null;
  inPipeline?: boolean | null;
  fillsTier?: string | null;
  fillsPoints?: string | null;
  liveVersion?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ai-step-versions".
 */
export interface AiStepVersion {
  id: number;
  step: number | AiStep;
  number: number;
  prompt: string;
  provider?: ('anthropic' | 'openai') | null;
  model?: string | null;
  temperature?: number | null;
  maxTokens?: number | null;
  note: string;
  author?: (number | null) | User;
  authorName?: string | null;
  authorRole?: string | null;
  live?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ai-step-outputs".
 */
export interface AiStepOutput {
  id: number;
  step?: (number | null) | AiStep;
  stepSlug: string;
  versionNumber?: number | null;
  lesson?: (number | null) | Lesson;
  mode?: ('try' | 'run') | null;
  disposition?: ('preview' | 'applied' | 'pending' | 'failed') | null;
  output?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  written?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  error?: string | null;
  job?: (number | null) | AiStepJob;
  protectsKind?: string | null;
  protectsId?: number | null;
  protectsReason?: string | null;
  mock?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ai-step-jobs".
 */
export interface AiStepJob {
  id: number;
  stepSlug: string;
  scope?: ('talk' | 'selection' | 'course' | 'all') | null;
  lessonIds?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  course?: (number | null) | Course;
  status?: ('queued' | 'running' | 'done' | 'failed') | null;
  total?: number | null;
  finished?: number | null;
  failedCount?: number | null;
  results?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  actor?: (number | null) | User;
  actorName?: string | null;
  note?: string | null;
  error?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ai-desk".
 */
export interface AiDesk {
  id: number;
  key: string;
  portalMayEdit?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "sheet-keys".
 */
export interface SheetKey {
  id: number;
  talkKey: string;
  lesson: number | Lesson;
  channel?: string | null;
  sheetStatus?: ('draft' | 'checked' | 'live') | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "sheet-imports".
 */
export interface SheetImport {
  id: number;
  desk: 'master' | 'portal';
  portal?: (number | null) | Portal;
  actor?: (number | null) | User;
  actorRole?: string | null;
  fileName?: string | null;
  state: 'preview' | 'applied' | 'undone';
  at?: string | null;
  summary?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  snapshot?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  workbook?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'portals';
        value: number | Portal;
      } | null)
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'clauses';
        value: number | Clause;
      } | null)
    | ({
        relationTo: 'doors';
        value: number | Door;
      } | null)
    | ({
        relationTo: 'seats';
        value: number | Seat;
      } | null)
    | ({
        relationTo: 'shelf-items';
        value: number | ShelfItem;
      } | null)
    | ({
        relationTo: 'speakers';
        value: number | Speaker;
      } | null)
    | ({
        relationTo: 'courses';
        value: number | Course;
      } | null)
    | ({
        relationTo: 'units';
        value: number | Unit;
      } | null)
    | ({
        relationTo: 'lessons';
        value: number | Lesson;
      } | null)
    | ({
        relationTo: 'resources';
        value: number | Resource;
      } | null)
    | ({
        relationTo: 'packs';
        value: number | Pack;
      } | null)
    | ({
        relationTo: 'cuts';
        value: number | Cut;
      } | null)
    | ({
        relationTo: 'ladder-items';
        value: number | LadderItem;
      } | null)
    | ({
        relationTo: 'engagement-points';
        value: number | EngagementPoint;
      } | null)
    | ({
        relationTo: 'answers';
        value: number | Answer;
      } | null)
    | ({
        relationTo: 'workbook-entries';
        value: number | WorkbookEntry;
      } | null)
    | ({
        relationTo: 'notifications';
        value: number | Notification;
      } | null)
    | ({
        relationTo: 'access-codes';
        value: number | AccessCode;
      } | null)
    | ({
        relationTo: 'talk-tiers';
        value: number | TalkTier;
      } | null)
    | ({
        relationTo: 'adoptions';
        value: number | Adoption;
      } | null)
    | ({
        relationTo: 'placing-questions';
        value: number | PlacingQuestion;
      } | null)
    | ({
        relationTo: 'placing-answers';
        value: number | PlacingAnswer;
      } | null)
    | ({
        relationTo: 'tags';
        value: number | Tag;
      } | null)
    | ({
        relationTo: 'harvest-entries';
        value: number | HarvestEntry;
      } | null)
    | ({
        relationTo: 'drawn-to';
        value: number | DrawnTo;
      } | null)
    | ({
        relationTo: 'schedules';
        value: number | Schedule;
      } | null)
    | ({
        relationTo: 'events';
        value: number | Event;
      } | null)
    | ({
        relationTo: 'rsvps';
        value: number | Rsvp;
      } | null)
    | ({
        relationTo: 'checkins';
        value: number | Checkin;
      } | null)
    | ({
        relationTo: 'messages';
        value: number | Message;
      } | null)
    | ({
        relationTo: 'completions';
        value: number | Completion;
      } | null)
    | ({
        relationTo: 'feedback-notes';
        value: number | FeedbackNote;
      } | null)
    | ({
        relationTo: 'watch-sessions';
        value: number | WatchSession;
      } | null)
    | ({
        relationTo: 'lesson-visits';
        value: number | LessonVisit;
      } | null)
    | ({
        relationTo: 'seat-visits';
        value: number | SeatVisit;
      } | null)
    | ({
        relationTo: 'rituals';
        value: number | Ritual;
      } | null)
    | ({
        relationTo: 'circle-answers';
        value: number | CircleAnswer;
      } | null)
    | ({
        relationTo: 'feedback-summaries';
        value: number | FeedbackSummary;
      } | null)
    | ({
        relationTo: 'question-rewrites';
        value: number | QuestionRewrite;
      } | null)
    | ({
        relationTo: 'scripture-cache';
        value: number | ScriptureCache;
      } | null)
    | ({
        relationTo: 'heart-scales';
        value: number | HeartScale;
      } | null)
    | ({
        relationTo: 'lanes';
        value: number | Lane;
      } | null)
    | ({
        relationTo: 'opening-scenes';
        value: number | OpeningScene;
      } | null)
    | ({
        relationTo: 'opening-configs';
        value: number | OpeningConfig;
      } | null)
    | ({
        relationTo: 'heart-states';
        value: number | HeartState;
      } | null)
    | ({
        relationTo: 'opening-answers';
        value: number | OpeningAnswer;
      } | null)
    | ({
        relationTo: 'heart-contributions';
        value: number | HeartContribution;
      } | null)
    | ({
        relationTo: 'view-as-sessions';
        value: number | ViewAsSession;
      } | null)
    | ({
        relationTo: 'audit-log';
        value: number | AuditLog;
      } | null)
    | ({
        relationTo: 'persona-bands';
        value: number | PersonaBand;
      } | null)
    | ({
        relationTo: 'compass-settings';
        value: number | CompassSetting;
      } | null)
    | ({
        relationTo: 'compass-attempts';
        value: number | CompassAttempt;
      } | null)
    | ({
        relationTo: 'compass-mixes';
        value: number | CompassMix;
      } | null)
    | ({
        relationTo: 'compass-serves';
        value: number | CompassServe;
      } | null)
    | ({
        relationTo: 'ai-steps';
        value: number | AiStep;
      } | null)
    | ({
        relationTo: 'ai-step-versions';
        value: number | AiStepVersion;
      } | null)
    | ({
        relationTo: 'ai-step-outputs';
        value: number | AiStepOutput;
      } | null)
    | ({
        relationTo: 'ai-step-jobs';
        value: number | AiStepJob;
      } | null)
    | ({
        relationTo: 'ai-desk';
        value: number | AiDesk;
      } | null)
    | ({
        relationTo: 'sheet-keys';
        value: number | SheetKey;
      } | null)
    | ({
        relationTo: 'sheet-imports';
        value: number | SheetImport;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "portals_select".
 */
export interface PortalsSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  kind?: T;
  welcome?: T;
  colour?: T;
  watchHistoryOptIn?: T;
  organisationName?: T;
  description?: T;
  closed?: T;
  logoUrl?: T;
  showOthersAnswers?: T;
  notificationEmails?: T;
  theme?: T;
  calendarUrl?: T;
  learnerWelcomeUrl?: T;
  learnerIntroUrl?: T;
  teacherWelcomeUrl?: T;
  teacherIntroUrl?: T;
  learnerLabel?: T;
  teacherLabel?: T;
  wizardDone?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T;
  role?: T;
  accessCode?: T;
  extraPacks?: T;
  onboarded?: T;
  seenWelcome?: T;
  startingClause?: T;
  courseList?: T;
  extraCourses?: T;
  audience?: T;
  shareWatch?: T;
  joinedAt?: T;
  nightAlerts?: T;
  shareOpening?: T;
  keepPlace?: T;
  trendsOptIn?: T;
  shareWithLearners?: T;
  haptics?: T;
  removed?: T;
  updatedBy?: T;
  onBehalfOf?: T;
  tenants?:
    | T
    | {
        tenant?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  resetPasswordRequestedAt?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  portal?: T;
  prefix?: T;
  _objectKey?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "clauses_select".
 */
export interface ClausesSelect<T extends boolean = true> {
  number?: T;
  fragment?: T;
  core?: T;
  teaching?: T;
  series?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "doors_select".
 */
export interface DoorsSelect<T extends boolean = true> {
  number?: T;
  section?: T;
  title?: T;
  clauses?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "seats_select".
 */
export interface SeatsSelect<T extends boolean = true> {
  clause?: T;
  position?: T;
  text?: T;
  note?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "shelf-items_select".
 */
export interface ShelfItemsSelect<T extends boolean = true> {
  volume?: T;
  section?: T;
  title?: T;
  series?: T;
  empty?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "speakers_select".
 */
export interface SpeakersSelect<T extends boolean = true> {
  name?: T;
  honorific?: T;
  displayName?: T;
  slug?: T;
  aliases?: T;
  bio?: T;
  photo?: T;
  photoUrl?: T;
  photoSource?: T;
  links?: T;
  sources?: T;
  status?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "courses_select".
 */
export interface CoursesSelect<T extends boolean = true> {
  title?: T;
  summary?: T;
  speaker?: T;
  speakerProfile?: T;
  origin?: T;
  portal?: T;
  importable?: T;
  isPublic?: T;
  importToken?: T;
  hidden?: T;
  visibility?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "units_select".
 */
export interface UnitsSelect<T extends boolean = true> {
  title?: T;
  course?: T;
  order?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "lessons_select".
 */
export interface LessonsSelect<T extends boolean = true> {
  title?: T;
  unit?: T;
  course?: T;
  portal?: T;
  master?: T;
  order?: T;
  speaker?: T;
  speakerProfile?: T;
  youtubeUrl?: T;
  youtubeId?: T;
  videoProvider?: T;
  vimeoId?: T;
  film?: T;
  muxAssetId?: T;
  muxPlaybackId?: T;
  durationSeconds?: T;
  transcript?: T;
  transcriptSource?: T;
  transcriptNote?: T;
  sourceUrl?: T;
  csvSeq?: T;
  starterLane?: T;
  sourceTitle?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "resources_select".
 */
export interface ResourcesSelect<T extends boolean = true> {
  lesson?: T;
  name?: T;
  kind?: T;
  url?: T;
  file?: T;
  body?: T;
  showAtEnd?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "packs_select".
 */
export interface PacksSelect<T extends boolean = true> {
  title?: T;
  summary?: T;
  owner?: T;
  portal?: T;
  courses?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "cuts_select".
 */
export interface CutsSelect<T extends boolean = true> {
  lesson?: T;
  course?: T;
  status?: T;
  placeholder?: T;
  presentation?: T;
  playable?: T;
  lastError?: T;
  start?: T;
  end?: T;
  timestamp?: T;
  hook?: T;
  turn?: T;
  land?: T;
  fullContext?: T;
  theme?: T;
  device?: T;
  whyItAllures?: T;
  bestClause?: T;
  clauseFragment?: T;
  hangStrength?: T;
  whyHang?: T;
  seatHint?: T;
  stage2Form?: T;
  currencyNote?: T;
  quoteConfidence?: T;
  exemplarAffinity?: T;
  kind?: T;
  engine?: T;
  seat?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ladder-items_select".
 */
export interface LadderItemsSelect<T extends boolean = true> {
  lesson?: T;
  cut?: T;
  kind?: T;
  start?: T;
  end?: T;
  quote?: T;
  parentRef?: T;
  status?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "engagement-points_select".
 */
export interface EngagementPointsSelect<T extends boolean = true> {
  lesson?: T;
  cut?: T;
  triggerType?: T;
  second?: T;
  nudges?: T;
  crisisOption?: T;
  correctOption?: T;
  timeLimitSec?: T;
  kind?: T;
  prompt?: T;
  options?: T;
  timing?: T;
  delayAmount?: T;
  delayUnit?: T;
  contingent?: T;
  link?: T;
  timeLimit?: T;
  author?: T;
  audience?: T;
  audienceUsers?: T;
  status?: T;
  draftNote?: T;
  reviewedBy?: T;
  family?: T;
  dueDays?: T;
  evidence?: T;
  showImam?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "answers_select".
 */
export interface AnswersSelect<T extends boolean = true> {
  portal?: T;
  point?: T;
  user?: T;
  lesson?: T;
  body?: T;
  choice?: T;
  image?: T;
  audio?: T;
  video?: T;
  keepPrivate?: T;
  shareWithTeacher?: T;
  shareWithLearners?: T;
  cut?: T;
  atSecond?: T;
  viewingId?: T;
  answeredAt?: T;
  pendingSync?: T;
  correct?: T;
  sourceLevel?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "workbook-entries_select".
 */
export interface WorkbookEntriesSelect<T extends boolean = true> {
  portal?: T;
  user?: T;
  answer?: T;
  lesson?: T;
  course?: T;
  body?: T;
  image?: T;
  consent?: T;
  teacherReply?: T;
  repliedAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "notifications_select".
 */
export interface NotificationsSelect<T extends boolean = true> {
  portal?: T;
  user?: T;
  title?: T;
  body?: T;
  href?: T;
  read?: T;
  channel?: T;
  key?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "access-codes_select".
 */
export interface AccessCodesSelect<T extends boolean = true> {
  portal?: T;
  code?: T;
  role?: T;
  packs?: T;
  requiredCourses?: T;
  linkedTeacherCode?: T;
  parentMentorCode?: T;
  label?: T;
  expiresAt?: T;
  maxUses?: T;
  uses?: T;
  disabled?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "talk-tiers_select".
 */
export interface TalkTiersSelect<T extends boolean = true> {
  lesson?: T;
  horsStart?: T;
  horsEnd?: T;
  horsQuote?: T;
  appetiserStart?: T;
  appetiserEnd?: T;
  hook?: T;
  turn?: T;
  land?: T;
  hookAt?: T;
  turnAt?: T;
  landAt?: T;
  appetiserSpans?: T;
  horsLines?: T;
  lineTidy?: T;
  typographyStyle?: T;
  typographyInPlace?: T;
  offerResume?: T;
  status?: T;
  checkedAt?: T;
  source?: T;
  note?: T;
  checkedBy?: T;
  parents?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "adoptions_select".
 */
export interface AdoptionsSelect<T extends boolean = true> {
  portal?: T;
  kind?: T;
  pack?: T;
  course?: T;
  hidden?: T;
  order?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "placing-questions_select".
 */
export interface PlacingQuestionsSelect<T extends boolean = true> {
  prompt?: T;
  why?: T;
  options?: T;
  order?: T;
  portal?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "placing-answers_select".
 */
export interface PlacingAnswersSelect<T extends boolean = true> {
  portal?: T;
  user?: T;
  question?: T;
  choice?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tags_select".
 */
export interface TagsSelect<T extends boolean = true> {
  item?: T;
  clause?: T;
  seat?: T;
  lane?: T;
  scale?: T;
  weight?: T;
  state?: T;
  note?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "harvest-entries_select".
 */
export interface HarvestEntriesSelect<T extends boolean = true> {
  portal?: T;
  user?: T;
  lesson?: T;
  kind?: T;
  text?: T;
  reference?: T;
  timestamp?: T;
  context?: T;
  seconds?: T;
  surah?: T;
  ayah?: T;
  matchedBy?: T;
  collection?: T;
  hadithNumber?: T;
  hadithText?: T;
  hadithArabic?: T;
  grading?: T;
  seenAt?: T;
  speaker?: T;
  door?: T;
  surface?: T;
  gatheredAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "drawn-to_select".
 */
export interface DrawnToSelect<T extends boolean = true> {
  portal?: T;
  user?: T;
  speaker?: T;
  speakerSlug?: T;
  linger?: T;
  learnMore?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "schedules_select".
 */
export interface SchedulesSelect<T extends boolean = true> {
  portal?: T;
  name?: T;
  owner?: T;
  learners?: T;
  targetType?: T;
  course?: T;
  pack?: T;
  startDate?: T;
  endDate?: T;
  weekdays?: T;
  slots?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "events_select".
 */
export interface EventsSelect<T extends boolean = true> {
  portal?: T;
  title?: T;
  startsAt?: T;
  place?: T;
  note?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "rsvps_select".
 */
export interface RsvpsSelect<T extends boolean = true> {
  portal?: T;
  event?: T;
  user?: T;
  status?: T;
  ticket?: T;
  ticketKind?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "checkins_select".
 */
export interface CheckinsSelect<T extends boolean = true> {
  portal?: T;
  event?: T;
  user?: T;
  override?: T;
  byStaff?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "messages_select".
 */
export interface MessagesSelect<T extends boolean = true> {
  portal?: T;
  author?: T;
  body?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "completions_select".
 */
export interface CompletionsSelect<T extends boolean = true> {
  portal?: T;
  user?: T;
  lesson?: T;
  percent?: T;
  onTime?: T;
  sourceLevel?: T;
  watchedAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "feedback-notes_select".
 */
export interface FeedbackNotesSelect<T extends boolean = true> {
  portal?: T;
  answer?: T;
  author?: T;
  second?: T;
  body?: T;
  audio?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "watch-sessions_select".
 */
export interface WatchSessionsSelect<T extends boolean = true> {
  portal?: T;
  user?: T;
  lesson?: T;
  seconds?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "lesson-visits_select".
 */
export interface LessonVisitsSelect<T extends boolean = true> {
  portal?: T;
  user?: T;
  lesson?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "seat-visits_select".
 */
export interface SeatVisitsSelect<T extends boolean = true> {
  portal?: T;
  user?: T;
  seat?: T;
  returned?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "rituals_select".
 */
export interface RitualsSelect<T extends boolean = true> {
  portal?: T;
  user?: T;
  note?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "circle-answers_select".
 */
export interface CircleAnswersSelect<T extends boolean = true> {
  point?: T;
  lesson?: T;
  portal?: T;
  name?: T;
  body?: T;
  tone?: T;
  length?: T;
  origin?: T;
  enabled?: T;
  author?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "feedback-summaries_select".
 */
export interface FeedbackSummariesSelect<T extends boolean = true> {
  portal?: T;
  point?: T;
  questionKey?: T;
  themes?: T;
  quotes?: T;
  status?: T;
  stepSlug?: T;
  versionNumber?: T;
  author?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "question-rewrites_select".
 */
export interface QuestionRewritesSelect<T extends boolean = true> {
  point?: T;
  prompt?: T;
  talk?: T;
  family?: T;
  reasons?: T;
  rewrite?: T;
  status?: T;
  author?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "scripture-cache_select".
 */
export interface ScriptureCacheSelect<T extends boolean = true> {
  key?: T;
  kind?: T;
  data?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "heart-scales_select".
 */
export interface HeartScalesSelect<T extends boolean = true> {
  key?: T;
  leonName?: T;
  room?: T;
  polishLabel?: T;
  focusName?: T;
  season?: T;
  firstOpenRead?: T;
  anchors?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "lanes_select".
 */
export interface LanesSelect<T extends boolean = true> {
  key?: T;
  title?: T;
  scale?: T;
  fit?: T;
  clauses?:
    | T
    | {
        clause?: T;
        rank?: T;
        id?: T;
      };
  seats?: T;
  seriesNote?: T;
  optInOnly?: T;
  excludeClauses?: T;
  order?: T;
  reachPhrase?: T;
  pseudo?: T;
  starters?:
    | T
    | {
        lesson?: T;
        role?: T;
        order?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "opening-scenes_select".
 */
export interface OpeningScenesSelect<T extends boolean = true> {
  key?: T;
  order?: T;
  caption?: T;
  subline?: T;
  scene?: T;
  layout?: T;
  options?:
    | T
    | {
        key?: T;
        label?: T;
        replyPill?: T;
        nudges?:
          | T
          | {
              scale?: T;
              delta?: T;
              id?: T;
            };
        intentLane?: T;
        spineFirst?: T;
        crisis?: T;
        sensitivity?: T;
        id?: T;
      };
  status?: T;
  version?: T;
  adaptedFrom?: T;
  monthCaption?: T;
  monthSubline?: T;
  monthLabels?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "opening-configs_select".
 */
export interface OpeningConfigsSelect<T extends boolean = true> {
  portal?: T;
  wording?:
    | T
    | {
        scene?: T;
        caption?: T;
        subline?: T;
        labels?: T;
        id?: T;
      };
  hiddenScenes?: T;
  defaultClip?: T;
  helpContacts?:
    | T
    | {
        label?: T;
        phone?: T;
        url?: T;
        hours?: T;
        id?: T;
      };
  trendsContributionPrompt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "heart-states_select".
 */
export interface HeartStatesSelect<T extends boolean = true> {
  user?: T;
  state?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "opening-answers_select".
 */
export interface OpeningAnswersSelect<T extends boolean = true> {
  user?: T;
  portal?: T;
  scene?: T;
  sceneKey?: T;
  optionKey?: T;
  labelSnapshot?: T;
  private?: T;
  staffVisible?: T;
  mentors?: T;
  scenesVersion?: T;
  answeredAt?: T;
  recordedAt?: T;
  supersededAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "heart-contributions_select".
 */
export interface HeartContributionsSelect<T extends boolean = true> {
  portal?: T;
  isoWeek?: T;
  doorKey?: T;
  scenePasses?: T;
  laneTop2?: T;
  nonceHash?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "view-as-sessions_select".
 */
export interface ViewAsSessionsSelect<T extends boolean = true> {
  actor?: T;
  actorRole?: T;
  target?: T;
  targetRole?: T;
  portal?: T;
  reason?: T;
  token?: T;
  startedAt?: T;
  lastSeenAt?: T;
  expiresAt?: T;
  endedAt?: T;
  endReason?: T;
  writeEnabled?: T;
  writeUntil?: T;
  returnTo?: T;
  ipHash?: T;
  userAgent?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "audit-log_select".
 */
export interface AuditLogSelect<T extends boolean = true> {
  event?: T;
  actor?: T;
  actorRole?: T;
  target?: T;
  targetRole?: T;
  portal?: T;
  sessionId?: T;
  reason?: T;
  at?: T;
  ipHash?: T;
  detail?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "persona-bands_select".
 */
export interface PersonaBandsSelect<T extends boolean = true> {
  key?: T;
  title?: T;
  status?: T;
  source?: T;
  placeholder?: T;
  identicalGroup?: T;
  note?: T;
  version?: T;
  description?: T;
  doors?: T;
  talks?: T;
  ranges?:
    | T
    | {
        scale?: T;
        present?: T;
        min?: T;
        max?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "compass-settings_select".
 */
export interface CompassSettingsSelect<T extends boolean = true> {
  key?: T;
  frame?: T;
  focusLead?: T;
  movementUp?: T;
  movementSame?: T;
  movementOnward?: T;
  lifeCaption?: T;
  lifeSubline?: T;
  places?:
    | T
    | {
        key?: T;
        label?: T;
        low?: T;
        high?: T;
        forward?: T;
        id?: T;
      };
  lifeOptions?:
    | T
    | {
        key?: T;
        label?: T;
        boost?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "compass-attempts_select".
 */
export interface CompassAttemptsSelect<T extends boolean = true> {
  user?: T;
  portal?: T;
  at?: T;
  bank?: T;
  lifeKey?: T;
  lifeKeys?: T;
  lifeNote?: T;
  formKey?: T;
  demoKey?: T;
  scales?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "compass-mixes_select".
 */
export interface CompassMixesSelect<T extends boolean = true> {
  portal?: T;
  deficit?: T;
  strength?: T;
  discovery?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "compass-serves_select".
 */
export interface CompassServesSelect<T extends boolean = true> {
  user?: T;
  portal?: T;
  lesson?: T;
  title?: T;
  kind?: T;
  why?: T;
  mix?: T;
  at?: T;
  door?: T;
  bucket?: T;
  demoKey?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ai-steps_select".
 */
export interface AiStepsSelect<T extends boolean = true> {
  slug?: T;
  name?: T;
  description?: T;
  placeholders?: T;
  prompt?: T;
  provider?: T;
  model?: T;
  temperature?: T;
  maxTokens?: T;
  outputSchema?: T;
  fills?: T;
  pipelineOrder?: T;
  inPipeline?: T;
  fillsTier?: T;
  fillsPoints?: T;
  liveVersion?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ai-step-versions_select".
 */
export interface AiStepVersionsSelect<T extends boolean = true> {
  step?: T;
  number?: T;
  prompt?: T;
  provider?: T;
  model?: T;
  temperature?: T;
  maxTokens?: T;
  note?: T;
  author?: T;
  authorName?: T;
  authorRole?: T;
  live?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ai-step-outputs_select".
 */
export interface AiStepOutputsSelect<T extends boolean = true> {
  step?: T;
  stepSlug?: T;
  versionNumber?: T;
  lesson?: T;
  mode?: T;
  disposition?: T;
  output?: T;
  written?: T;
  error?: T;
  job?: T;
  protectsKind?: T;
  protectsId?: T;
  protectsReason?: T;
  mock?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ai-step-jobs_select".
 */
export interface AiStepJobsSelect<T extends boolean = true> {
  stepSlug?: T;
  scope?: T;
  lessonIds?: T;
  course?: T;
  status?: T;
  total?: T;
  finished?: T;
  failedCount?: T;
  results?: T;
  actor?: T;
  actorName?: T;
  note?: T;
  error?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ai-desk_select".
 */
export interface AiDeskSelect<T extends boolean = true> {
  key?: T;
  portalMayEdit?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "sheet-keys_select".
 */
export interface SheetKeysSelect<T extends boolean = true> {
  talkKey?: T;
  lesson?: T;
  channel?: T;
  sheetStatus?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "sheet-imports_select".
 */
export interface SheetImportsSelect<T extends boolean = true> {
  desk?: T;
  portal?: T;
  actor?: T;
  actorRole?: T;
  fileName?: T;
  state?: T;
  at?: T;
  summary?: T;
  snapshot?: T;
  workbook?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "master-flags".
 */
export interface MasterFlag {
  id: number;
  /**
   * Pop-up questions sit over the YouTube player, as in the old system. Off: the card fills the screen below the paused player (YouTube’s embed rules).
   */
  popupOverPlayer?: boolean | null;
  /**
   * The board’s full-bleed look: caption, right rail, speaker bar and gold pill over the clip. Off: all of it sits around the player.
   */
  chromeOverPlayer?: boolean | null;
  /**
   * Show unchecked talks to learners. On, draft tiers play in the feed. Off (the default for production), only talks a person has approved on the review desk play.
   */
  showUnchecked?: boolean | null;
  /**
   * The light label under each HEARTS circle answer in the swarm.
   */
  circleLabel?: string | null;
  /**
   * Circle answers show less often as real shared answers arrive, and step back once a question has this many.
   */
  circleThreshold?: number | null;
  /**
   * Longest hors d'oeuvre the desk will save, in seconds. 15 to 30 is the usual length; longer is only a warning. Longer than this is refused.
   */
  horsMaxSeconds?: number | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "master-flags_select".
 */
export interface MasterFlagsSelect<T extends boolean = true> {
  popupOverPlayer?: T;
  chromeOverPlayer?: T;
  showUnchecked?: T;
  circleLabel?: T;
  circleThreshold?: T;
  horsMaxSeconds?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}