import { unlink } from 'node:fs/promises'
import path from 'node:path'
import { DeleteObjectCommand, S3Client } from '@aws-sdk/client-s3'
import type { Payload } from 'payload'
import { databaseKind, readS3 } from '../../lib/env'
import { bind, execOutside, quoteIdent } from './sql'
import type { MediaTarget, SqlExec } from './types'

const RETRY_COLUMNS = `
  object_key varchar NOT NULL,
  bucket varchar,
  filename varchar,
  local_path varchar,
  error varchar,
  created_at timestamp DEFAULT CURRENT_TIMESTAMP,
  attempts integer DEFAULT 0
`

const RETRY_TABLE_SQLITE = `
CREATE TABLE IF NOT EXISTS erase_s3_retries (
  id integer PRIMARY KEY,
  ${RETRY_COLUMNS}
)
`

const RETRY_TABLE_POSTGRES = `
CREATE TABLE IF NOT EXISTS erase_s3_retries (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  ${RETRY_COLUMNS}
)
`

function objectKey(file: MediaTarget) {
  if (file.objectKey) return file.objectKey
  const prefix = String(file.prefix || '').replace(/^\/+|\/+$/g, '')
  const name = String(file.filename || '')
  if (!name) return ''
  return prefix ? `${prefix}/${name}` : name
}

function localPath(file: MediaTarget) {
  const name = String(file.filename || '')
  if (!name) return ''
  return path.resolve(process.cwd(), 'media', name)
}

export async function collectMedia(exec: SqlExec, ids: number[]) {
  const unique = [...new Set(ids.filter((id) => Number.isInteger(id) && id > 0))]
  if (!unique.length) return [] as MediaTarget[]
  const found = await exec(`SELECT id, filename, prefix, url, _objectkey AS "objectKey" FROM media WHERE id IN (${unique.join(',')})`)
  return found.rows as unknown as MediaTarget[]
}

export async function mediaIdsFrom(exec: SqlExec, table: string, columns: string[], where: string) {
  const ids: number[] = []
  for (const column of columns) {
    const result = await exec(`SELECT ${quoteIdent(column)} AS id FROM ${quoteIdent(table)} WHERE ${where} AND ${quoteIdent(column)} IS NOT NULL`)
    for (const row of result.rows) {
      const id = Number(row.id)
      if (Number.isInteger(id) && id > 0) ids.push(id)
    }
  }
  return ids
}

export async function unreferencedPortalMedia(exec: SqlExec, portalId: number) {
  const sql = bind(
    `SELECT id, filename, prefix, url, _objectkey AS "objectKey" FROM media
     WHERE portal_id = {id}
       AND id NOT IN (SELECT photo_id FROM speakers WHERE photo_id IS NOT NULL)
       AND id NOT IN (SELECT film_id FROM lessons WHERE film_id IS NOT NULL)
       AND id NOT IN (SELECT file_id FROM resources WHERE file_id IS NOT NULL)
       AND id NOT IN (SELECT scene_id FROM opening_scenes WHERE scene_id IS NOT NULL)`,
    portalId,
    'portal',
  )
  return (await exec(sql)).rows as unknown as MediaTarget[]
}

export async function ensureRetryTable(payload: Payload) {
  if (databaseKind() === 'postgres') {
    const identity = await execOutside(
      payload,
      `SELECT is_identity FROM information_schema.columns
       WHERE table_schema = 'public' AND table_name = 'erase_s3_retries' AND column_name = 'id'`,
    ).catch(() => ({ rows: [] as Record<string, unknown>[] }))
    if (identity.rows.length && String(identity.rows[0]?.is_identity || '').toUpperCase() !== 'YES') {
      await execOutside(payload, 'DROP TABLE IF EXISTS erase_s3_retries').catch(() => undefined)
    }
    await execOutside(payload, RETRY_TABLE_POSTGRES).catch(() => undefined)
    return
  }
  await execOutside(payload, RETRY_TABLE_SQLITE).catch(() => undefined)
}

function retrySql(file: MediaTarget, bucket: string, error: string, local: string) {
  const key = objectKey(file).replaceAll("'", "''")
  const err = error.replaceAll("'", "''").slice(0, 500)
  const fileName = String(file.filename || '').replaceAll("'", "''")
  const bucketName = bucket.replaceAll("'", "''")
  const localName = local.replaceAll("'", "''")
  return `INSERT INTO erase_s3_retries (object_key, bucket, filename, local_path, error, attempts) VALUES ('${key}', '${bucketName}', '${fileName}', '${localName}', '${err}', 1)`
}

async function deleteOne(file: MediaTarget) {
  if (process.env.HEARTS_ERASE_FAIL_STORAGE === '1') throw new Error('Forced storage failure for tests.')
  const s3 = readS3()
  const key = objectKey(file)
  const disk = localPath(file)
  if (s3 && key) {
    const client = new S3Client({
      credentials: { accessKeyId: s3.accessKeyId, secretAccessKey: s3.secretAccessKey },
      region: s3.region,
      endpoint: s3.endpoint,
      forcePathStyle: s3.forcePathStyle,
    })
    await client.send(new DeleteObjectCommand({ Bucket: s3.bucket, Key: key }))
    return
  }
  if (disk) {
    await unlink(disk).catch((error: { code?: string }) => {
      if (error.code !== 'ENOENT') throw error
    })
  }
}

export async function removeStoredFiles(payload: Payload, files: MediaTarget[]) {
  const s3 = readS3()
  let removed = 0
  let failed = 0
  await ensureRetryTable(payload)
  for (const file of files) {
    const disk = localPath(file)
    try {
      await deleteOne(file)
      removed += 1
    } catch (error) {
      failed += 1
      const message = error instanceof Error ? error.message : 'The file could not be removed.'
      await execOutside(payload, retrySql(file, s3?.bucket || '', message, disk)).catch(() => undefined)
    }
  }
  return { removed, failed }
}

export async function retryFailedFiles(payload: Payload) {
  await ensureRetryTable(payload)
  const listed = await execOutside(payload, 'SELECT id, object_key, bucket, filename, local_path, error, attempts FROM erase_s3_retries').catch(() => ({ rows: [] as Record<string, unknown>[] }))
  let removed = 0
  let failed = 0
  for (const row of listed.rows) {
    const file: MediaTarget = {
      id: 0,
      filename: String(row.filename || ''),
      objectKey: String(row.object_key || ''),
      prefix: '',
    }
    try {
      await deleteOne(file)
      await execOutside(payload, `DELETE FROM erase_s3_retries WHERE id = ${Number(row.id)}`)
      removed += 1
    } catch (error) {
      failed += 1
      const message = error instanceof Error ? error.message : 'The file could not be removed.'
      await execOutside(
        payload,
        `UPDATE erase_s3_retries SET attempts = ${(Number(row.attempts) || 0) + 1}, error = '${message.replaceAll("'", "''").slice(0, 500)}' WHERE id = ${Number(row.id)}`,
      ).catch(() => undefined)
    }
  }
  return { removed, failed, queued: listed.rows.length }
}
